<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Xcart\\External_Product_Verification\\' => array($baseDir . '/modules/External_Product_Verification/include'),
    'Xcart\\External_Marketplaces\\' => array($baseDir . '/modules/External_Marketplaces/include'),
    'Xcart\\' => array($baseDir . '/include/Xcart'),
    'Ups\\' => array($vendorDir . '/gabrielbull/ups-api/src/Ups'),
    'TrueBV\\' => array($vendorDir . '/true/punycode/src'),
    'TheIconic\\Tracking\\GoogleAnalytics\\' => array($vendorDir . '/theiconic/php-ga-measurement-protocol/src'),
    'Symfony\\Polyfill\\Php55\\' => array($vendorDir . '/symfony/polyfill-php55'),
    'Symfony\\Polyfill\\Php54\\' => array($vendorDir . '/symfony/polyfill-php54'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Validator\\' => array($vendorDir . '/symfony/validator'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Omnipay\\PayPal\\' => array($baseDir . '/app/Modules/Payment/Gateways/Omnipay/PayPal', $vendorDir . '/omnipay/paypal/src'),
    'Omnipay\\BluePay\\' => array($baseDir . '/app/Modules/Payment/Gateways/Omnipay/BluePay'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Modules\\' => array($baseDir . '/app/Modules'),
    'Mindy\\QueryBuilder\\' => array($vendorDir . '/mindy/query_builder/src'),
    'League\\Flysystem\\' => array($vendorDir . '/league/flysystem/src'),
    'Jaybizzle\\CrawlerDetect\\' => array($vendorDir . '/jaybizzle/crawler-detect/src'),
    'GuzzleHttp\\Stream\\' => array($vendorDir . '/guzzlehttp/streams/src'),
    'GuzzleHttp\\Ring\\' => array($vendorDir . '/guzzlehttp/ringphp/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
    'Cocur\\Slugify\\' => array($vendorDir . '/cocur/slugify/src'),
);
