<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        'e40631d46120a9c38ea139981f8dab26' => __DIR__ . '/..' . '/ircmaxell/password-compat/lib/password.php',
        '2c102faa651ef8ea5874edb585946bce' => __DIR__ . '/..' . '/swiftmailer/swiftmailer/lib/swift_required.php',
        'edc6464955a37aa4d5fbf39d40fb6ee7' => __DIR__ . '/..' . '/symfony/polyfill-php55/bootstrap.php',
        '3e2471375464aac821502deb0ac64275' => __DIR__ . '/..' . '/symfony/polyfill-php54/bootstrap.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
        '68f9084e889ebf718663435970ab45e3' => __DIR__ . '/..' . '/mindy/query_builder/src/Conditions.php',
        '38aa9ffa312700065ceed8bf7bcb7a53' => __DIR__ . '/../../..' . '/include/func/func.core.php',
        'f550ebde9e69876a00625883277835ce' => __DIR__ . '/../../..' . '/include/func/func.amazon.php',
        'dca41d7b610d234855ab845f35115f14' => __DIR__ . '/../../..' . '/include/func/func.amazon_shipping.php',
        'c074bc0f3f52cf1c23cb50d0b4b45a7d' => __DIR__ . '/../../..' . '/include/func/func.backoffice.php',
        'c735e56e84931684b20d9a61359574fb' => __DIR__ . '/../../..' . '/include/func/func.cart.php',
        '4fe8cfc3c08ff324bbca0dc5a2183eb2' => __DIR__ . '/../../..' . '/include/func/func.category.php',
        '7a0f7bab0b4c07a48efbd41ed882e12c' => __DIR__ . '/../../..' . '/include/func/func.clean_urls.php',
        '2e533e5cb2c07d8428158b9e0b1a8f59' => __DIR__ . '/../../..' . '/include/func/func.crypt.php',
        '77051ec6f375af33ee9a9812c74448bf' => __DIR__ . '/../../..' . '/include/func/func.db.php',
        '1f6b825d735402a45f92496cd075653e' => __DIR__ . '/../../..' . '/include/func/func.debug.php',
        '697d63fd5a525232af8e966a1be1059c' => __DIR__ . '/../../..' . '/include/func/func.export.php',
        '4adcbdf83ad97c61a32666548447b10e' => __DIR__ . '/../../..' . '/include/func/func.files.php',
        'ac35a74c3508918853d2004669f1c05a' => __DIR__ . '/../../..' . '/include/func/func.fraud.php',
        '4f893e9c6a947e25f96c5e139bc5cf3d' => __DIR__ . '/../../..' . '/include/func/func.froogle.php',
        'a98b2562f5334952ccc83cd6c2b0cbd3' => __DIR__ . '/../../..' . '/include/func/func.gd.php',
        'd324cee2ece3cf9e5f2322d42cfdff38' => __DIR__ . '/../../..' . '/include/func/func.http.php',
        'dc42f8b8545788e38401347f9114ea93' => __DIR__ . '/../../..' . '/include/func/func.https_curl.php',
        '631dd34c8ce264611ac30d6287265ec0' => __DIR__ . '/../../..' . '/include/func/func.https_httpscli.php',
        'a33f592b4c44fb72c8360271220c4c4b' => __DIR__ . '/../../..' . '/include/func/func.https_libcurl.php',
        'e253c01efb77a61fbfc0519e877f00e9' => __DIR__ . '/../../..' . '/include/func/func.https_openssl.php',
        'add00bd7c7e925fa77868dfaf674a32d' => __DIR__ . '/../../..' . '/include/func/func.https_ssleay.php',
        '5f8e7042a87b85cfc6f2ef727b7894fa' => __DIR__ . '/../../..' . '/include/func/func.image.php',
        'e795ed7bab7715b7597022371a62c8f9' => __DIR__ . '/../../..' . '/include/func/func.import.php',
        '83b744f1987ac050e1aa79e9dfd286b4' => __DIR__ . '/../../..' . '/include/func/func.mail.php',
        '96fe48a4cf0e8647d8aa17a0e134b8a0' => __DIR__ . '/../../..' . '/include/func/func.order.php',
        '49c17c188cf012fc294a8bf1c3848a8d' => __DIR__ . '/../../..' . '/include/func/func.order_edit.php',
        '197f91b90ff50d598ea003293247f7d2' => __DIR__ . '/../../..' . '/include/func/func.payment.php',
        '6429a7127e4af112a87ff616b7363a2d' => __DIR__ . '/../../..' . '/include/func/func.product.php',
        'd9eb0d5fec929766b1eaa87d846a00b6' => __DIR__ . '/../../..' . '/include/func/func.snapshots.php',
        '958783f5a2a344d8c8bc789f72d27479' => __DIR__ . '/../../..' . '/include/func/func.taxes.php',
        '69094f3c2fec7461e41a47629a2de28d' => __DIR__ . '/../../..' . '/include/func/func.templater.php',
        '1bb638beed06175065baa2bc4f63664f' => __DIR__ . '/../../..' . '/include/func/func.tests.php',
        '5b62f9c3da43101dc7118a6037304d31' => __DIR__ . '/../../..' . '/include/func/func.user.php',
        '21d3e9b4840c61de5fb4b983afb6405d' => __DIR__ . '/../../..' . '/include/func/func.xml.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'X' => 
        array (
            'Xcart\\External_Product_Verification\\' => 36,
            'Xcart\\External_Marketplaces\\' => 28,
            'Xcart\\' => 6,
        ),
        'U' => 
        array (
            'Ups\\' => 4,
        ),
        'T' => 
        array (
            'TrueBV\\' => 7,
            'TheIconic\\Tracking\\GoogleAnalytics\\' => 35,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php55\\' => 23,
            'Symfony\\Polyfill\\Php54\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Validator\\' => 28,
            'Symfony\\Component\\Translation\\' => 30,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\Finder\\' => 25,
            'Symfony\\Component\\EventDispatcher\\' => 34,
        ),
        'R' => 
        array (
            'React\\Promise\\' => 14,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Cache\\' => 10,
        ),
        'O' => 
        array (
            'Omnipay\\PayPal\\' => 15,
            'Omnipay\\BluePay\\' => 16,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
            'Modules\\' => 8,
            'Mindy\\QueryBuilder\\' => 19,
            'MaxMind\\WebService\\' => 19,
            'MaxMind\\Exception\\' => 18,
            'MaxMind\\Db\\' => 11,
        ),
        'L' => 
        array (
            'League\\Flysystem\\' => 17,
        ),
        'J' => 
        array (
            'Jaybizzle\\CrawlerDetect\\' => 24,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Ring\\' => 16,
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\' => 11,
            'Google\\Auth\\' => 12,
            'GeoIp2\\' => 7,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Cache\\' => 22,
            'Dariuszp\\' => 9,
        ),
        'C' => 
        array (
            'Composer\\CaBundle\\' => 18,
            'Cocur\\Slugify\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'Xcart\\External_Product_Verification\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/modules/External_Product_Verification/include',
        ),
        'Xcart\\External_Marketplaces\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/modules/External_Marketplaces/include',
        ),
        'Xcart\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/include/Xcart',
        ),
        'Ups\\' => 
        array (
            0 => __DIR__ . '/..' . '/gabrielbull/ups-api/src/Ups',
        ),
        'TrueBV\\' => 
        array (
            0 => __DIR__ . '/..' . '/true/punycode/src',
        ),
        'TheIconic\\Tracking\\GoogleAnalytics\\' => 
        array (
            0 => __DIR__ . '/..' . '/theiconic/php-ga-measurement-protocol/src',
        ),
        'Symfony\\Polyfill\\Php55\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php55',
        ),
        'Symfony\\Polyfill\\Php54\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php54',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Validator\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/validator',
        ),
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Omnipay\\PayPal\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Modules/Payment/Gateways/Omnipay/PayPal',
            1 => __DIR__ . '/..' . '/omnipay/paypal/src',
        ),
        'Omnipay\\BluePay\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Modules/Payment/Gateways/Omnipay/BluePay',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Modules\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Modules',
        ),
        'Mindy\\QueryBuilder\\' => 
        array (
            0 => __DIR__ . '/..' . '/mindy/query_builder/src',
        ),
        'MaxMind\\WebService\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src/WebService',
        ),
        'MaxMind\\Exception\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src/Exception',
        ),
        'MaxMind\\Db\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind-db/reader/src/MaxMind/Db',
        ),
        'League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
        'Jaybizzle\\CrawlerDetect\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaybizzle/crawler-detect/src',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Ring\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/ringphp/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/auth/src',
        ),
        'GeoIp2\\' => 
        array (
            0 => __DIR__ . '/..' . '/geoip2/geoip2/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'Dariuszp\\' => 
        array (
            0 => __DIR__ . '/..' . '/dariuszp/cli-progress-bar/src/Dariuszp',
        ),
        'Composer\\CaBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/ca-bundle/src',
        ),
        'Cocur\\Slugify\\' => 
        array (
            0 => __DIR__ . '/..' . '/cocur/slugify/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
        'O' => 
        array (
            'Omnipay\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/omnipay/common/src',
            ),
        ),
        'I' => 
        array (
            'Imagine' => 
            array (
                0 => __DIR__ . '/..' . '/imagine/imagine/lib',
            ),
        ),
        'G' => 
        array (
            'Guzzle\\Tests' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/tests',
            ),
            'Guzzle' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/src',
            ),
            'Google_Service_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient-services/src',
            ),
            'Google_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient/src',
            ),
        ),
        'F' => 
        array (
            'Fenom\\' => 
            array (
                0 => __DIR__ . '/..' . '/fenom/fenom/src',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Inflector\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/inflector/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
            'Doctrine\\Common\\Annotations\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/annotations/lib',
            ),
            'Doctrine\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/common/lib',
            ),
            'Detection' => 
            array (
                0 => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/namespaced',
            ),
        ),
        'C' => 
        array (
            'CaponicaAmazonMwsComplete\\' => 
            array (
                0 => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src',
            ),
        ),
    );

    public static $classMap = array (
        'CallbackFilterIterator' => __DIR__ . '/..' . '/symfony/polyfill-php54/Resources/stubs/CallbackFilterIterator.php',
        'FBAInventoryServiceMWS_Client' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Client.php',
        'FBAInventoryServiceMWS_Exception' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Exception.php',
        'FBAInventoryServiceMWS_Interface' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Interface.php',
        'FBAInventoryServiceMWS_Mock' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Mock.php',
        'FBAInventoryServiceMWS_Model' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/GetServiceStatusResult.php',
        'FBAInventoryServiceMWS_Model_InventorySupply' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupply.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyDetail' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupplyDetail.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyDetailList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupplyDetailList.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupplyList.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenRequest.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenResponse.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenResult.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyRequest.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyResponse.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyResult.php',
        'FBAInventoryServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAInventoryServiceMWS_Model_ResponseMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ResponseMetadata.php',
        'FBAInventoryServiceMWS_Model_SellerSkuList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/SellerSkuList.php',
        'FBAInventoryServiceMWS_Model_Timepoint' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/Timepoint.php',
        'FBAOutboundServiceMWS_Client' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Client.php',
        'FBAOutboundServiceMWS_Exception' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Exception.php',
        'FBAOutboundServiceMWS_Interface' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Interface.php',
        'FBAOutboundServiceMWS_Mock' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Mock.php',
        'FBAOutboundServiceMWS_Model' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model.php',
        'FBAOutboundServiceMWS_Model_Address' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Address.php',
        'FBAOutboundServiceMWS_Model_CODSettings' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CODSettings.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentReturnRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentReturnRequest.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentReturnResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentReturnResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentReturnResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentReturnResult.php',
        'FBAOutboundServiceMWS_Model_CreateReturnItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateReturnItem.php',
        'FBAOutboundServiceMWS_Model_CreateReturnItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateReturnItemList.php',
        'FBAOutboundServiceMWS_Model_Currency' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Currency.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindow' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/DeliveryWindow.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindowList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/DeliveryWindowList.php',
        'FBAOutboundServiceMWS_Model_Fee' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Fee.php',
        'FBAOutboundServiceMWS_Model_FeeList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FeeList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentMethodList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentMethodList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrder' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrder.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrderList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreview' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreview.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipment' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipmentList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipment' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackage' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackage.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackageList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackageList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResult.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResult.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsRequest.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResponse.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResult.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetServiceStatusResult.php',
        'FBAOutboundServiceMWS_Model_InvalidItemReason' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/InvalidItemReason.php',
        'FBAOutboundServiceMWS_Model_InvalidReturnItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/InvalidReturnItem.php',
        'FBAOutboundServiceMWS_Model_InvalidReturnItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/InvalidReturnItemList.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResult.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResult.php',
        'FBAOutboundServiceMWS_Model_ListReturnReasonCodesRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListReturnReasonCodesRequest.php',
        'FBAOutboundServiceMWS_Model_ListReturnReasonCodesResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListReturnReasonCodesResponse.php',
        'FBAOutboundServiceMWS_Model_ListReturnReasonCodesResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListReturnReasonCodesResult.php',
        'FBAOutboundServiceMWS_Model_NotificationEmailList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/NotificationEmailList.php',
        'FBAOutboundServiceMWS_Model_ReasonCodeDetails' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReasonCodeDetails.php',
        'FBAOutboundServiceMWS_Model_ReasonCodeDetailsList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReasonCodeDetailsList.php',
        'FBAOutboundServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAOutboundServiceMWS_Model_ResponseMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ResponseMetadata.php',
        'FBAOutboundServiceMWS_Model_ReturnAuthorization' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnAuthorization.php',
        'FBAOutboundServiceMWS_Model_ReturnAuthorizationList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnAuthorizationList.php',
        'FBAOutboundServiceMWS_Model_ReturnItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnItem.php',
        'FBAOutboundServiceMWS_Model_ReturnItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnItemList.php',
        'FBAOutboundServiceMWS_Model_ScheduledDeliveryInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ScheduledDeliveryInfo.php',
        'FBAOutboundServiceMWS_Model_ShippingSpeedCategoryList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ShippingSpeedCategoryList.php',
        'FBAOutboundServiceMWS_Model_StringList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/StringList.php',
        'FBAOutboundServiceMWS_Model_TrackingAddress' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/TrackingAddress.php',
        'FBAOutboundServiceMWS_Model_TrackingEvent' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/TrackingEvent.php',
        'FBAOutboundServiceMWS_Model_TrackingEventList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/TrackingEventList.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItem.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_Weight' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Weight.php',
        'Fenom' => __DIR__ . '/..' . '/fenom/fenom/src/Fenom.php',
        'Google_Service_Exception' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Exception.php',
        'Google_Service_Resource' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Resource.php',
        'MarketplaceWebService_Client' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Client.php',
        'MarketplaceWebService_Exception' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Exception.php',
        'MarketplaceWebService_Interface' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Interface.php',
        'MarketplaceWebService_Mock' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Mock.php',
        'MarketplaceWebService_Model' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelFeedSubmissionsRequest.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelFeedSubmissionsResponse.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelFeedSubmissionsResult.php',
        'MarketplaceWebService_Model_CancelReportRequestsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelReportRequestsRequest.php',
        'MarketplaceWebService_Model_CancelReportRequestsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelReportRequestsResponse.php',
        'MarketplaceWebService_Model_CancelReportRequestsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelReportRequestsResult.php',
        'MarketplaceWebService_Model_ContentType' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ContentType.php',
        'MarketplaceWebService_Model_Error' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/Error.php',
        'MarketplaceWebService_Model_ErrorResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ErrorResponse.php',
        'MarketplaceWebService_Model_FeedSubmissionInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/FeedSubmissionInfo.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionCountRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionCountResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionCountResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionResultRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionResultResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionResultResult.php',
        'MarketplaceWebService_Model_GetReportCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportCountRequest.php',
        'MarketplaceWebService_Model_GetReportCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportCountResponse.php',
        'MarketplaceWebService_Model_GetReportCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportCountResult.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListRequest.php',
        'MarketplaceWebService_Model_GetReportListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListResponse.php',
        'MarketplaceWebService_Model_GetReportListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListResult.php',
        'MarketplaceWebService_Model_GetReportRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestCountRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestCountResponse.php',
        'MarketplaceWebService_Model_GetReportRequestCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestCountResult.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportRequestListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListResult.php',
        'MarketplaceWebService_Model_GetReportResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportResponse.php',
        'MarketplaceWebService_Model_GetReportResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportResult.php',
        'MarketplaceWebService_Model_GetReportScheduleCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleCountRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleCountResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleCountResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListResult.php',
        'MarketplaceWebService_Model_IdList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/IdList.php',
        'MarketplaceWebService_Model_ManageReportScheduleRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ManageReportScheduleRequest.php',
        'MarketplaceWebService_Model_ManageReportScheduleResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ManageReportScheduleResponse.php',
        'MarketplaceWebService_Model_ManageReportScheduleResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ManageReportScheduleResult.php',
        'MarketplaceWebService_Model_ReportInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ReportInfo.php',
        'MarketplaceWebService_Model_ReportRequestInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ReportRequestInfo.php',
        'MarketplaceWebService_Model_ReportSchedule' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ReportSchedule.php',
        'MarketplaceWebService_Model_RequestReportRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/RequestReportRequest.php',
        'MarketplaceWebService_Model_RequestReportResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/RequestReportResponse.php',
        'MarketplaceWebService_Model_RequestReportResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/RequestReportResult.php',
        'MarketplaceWebService_Model_ResponseHeaderMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ResponseHeaderMetadata.php',
        'MarketplaceWebService_Model_ResponseMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ResponseMetadata.php',
        'MarketplaceWebService_Model_StatusList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/StatusList.php',
        'MarketplaceWebService_Model_SubmitFeedRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/SubmitFeedRequest.php',
        'MarketplaceWebService_Model_SubmitFeedResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/SubmitFeedResponse.php',
        'MarketplaceWebService_Model_SubmitFeedResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/SubmitFeedResult.php',
        'MarketplaceWebService_Model_TypeList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/TypeList.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/UpdateReportAcknowledgementsRequest.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/UpdateReportAcknowledgementsResponse.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/UpdateReportAcknowledgementsResult.php',
        'Mobile_Detect' => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/Mobile_Detect.php',
        'Omnipay\\Omnipay' => __DIR__ . '/..' . '/omnipay/common/src/Omnipay/Omnipay.php',
        'RecursiveCallbackFilterIterator' => __DIR__ . '/..' . '/symfony/polyfill-php54/Resources/stubs/RecursiveCallbackFilterIterator.php',
        'RequestType' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/RequestType.php',
        'SessionHandlerInterface' => __DIR__ . '/..' . '/symfony/polyfill-php54/Resources/stubs/SessionHandlerInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixesPsr0;
            $loader->classMap = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$classMap;

        }, null, ClassLoader::class);
    }
}
