<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92
{
    public static $files = array (
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
        '68f9084e889ebf718663435970ab45e3' => __DIR__ . '/..' . '/mindy/query_builder/src/Conditions.php',
        '38aa9ffa312700065ceed8bf7bcb7a53' => __DIR__ . '/../../..' . '/include/func/func.core.php',
        'f550ebde9e69876a00625883277835ce' => __DIR__ . '/../../..' . '/include/func/func.amazon.php',
        'dca41d7b610d234855ab845f35115f14' => __DIR__ . '/../../..' . '/include/func/func.amazon_shipping.php',
        'c074bc0f3f52cf1c23cb50d0b4b45a7d' => __DIR__ . '/../../..' . '/include/func/func.backoffice.php',
        'c735e56e84931684b20d9a61359574fb' => __DIR__ . '/../../..' . '/include/func/func.cart.php',
        '4fe8cfc3c08ff324bbca0dc5a2183eb2' => __DIR__ . '/../../..' . '/include/func/func.category.php',
        '7a0f7bab0b4c07a48efbd41ed882e12c' => __DIR__ . '/../../..' . '/include/func/func.clean_urls.php',
        '2e533e5cb2c07d8428158b9e0b1a8f59' => __DIR__ . '/../../..' . '/include/func/func.crypt.php',
        '77051ec6f375af33ee9a9812c74448bf' => __DIR__ . '/../../..' . '/include/func/func.db.php',
        '1f6b825d735402a45f92496cd075653e' => __DIR__ . '/../../..' . '/include/func/func.debug.php',
        '697d63fd5a525232af8e966a1be1059c' => __DIR__ . '/../../..' . '/include/func/func.export.php',
        '4adcbdf83ad97c61a32666548447b10e' => __DIR__ . '/../../..' . '/include/func/func.files.php',
        'ac35a74c3508918853d2004669f1c05a' => __DIR__ . '/../../..' . '/include/func/func.fraud.php',
        '4f893e9c6a947e25f96c5e139bc5cf3d' => __DIR__ . '/../../..' . '/include/func/func.froogle.php',
        'a98b2562f5334952ccc83cd6c2b0cbd3' => __DIR__ . '/../../..' . '/include/func/func.gd.php',
        'd324cee2ece3cf9e5f2322d42cfdff38' => __DIR__ . '/../../..' . '/include/func/func.http.php',
        'dc42f8b8545788e38401347f9114ea93' => __DIR__ . '/../../..' . '/include/func/func.https_curl.php',
        '631dd34c8ce264611ac30d6287265ec0' => __DIR__ . '/../../..' . '/include/func/func.https_httpscli.php',
        'a33f592b4c44fb72c8360271220c4c4b' => __DIR__ . '/../../..' . '/include/func/func.https_libcurl.php',
        'e253c01efb77a61fbfc0519e877f00e9' => __DIR__ . '/../../..' . '/include/func/func.https_openssl.php',
        'add00bd7c7e925fa77868dfaf674a32d' => __DIR__ . '/../../..' . '/include/func/func.https_ssleay.php',
        '5f8e7042a87b85cfc6f2ef727b7894fa' => __DIR__ . '/../../..' . '/include/func/func.image.php',
        'e795ed7bab7715b7597022371a62c8f9' => __DIR__ . '/../../..' . '/include/func/func.import.php',
        '83b744f1987ac050e1aa79e9dfd286b4' => __DIR__ . '/../../..' . '/include/func/func.mail.php',
        '96fe48a4cf0e8647d8aa17a0e134b8a0' => __DIR__ . '/../../..' . '/include/func/func.order.php',
        '49c17c188cf012fc294a8bf1c3848a8d' => __DIR__ . '/../../..' . '/include/func/func.order_edit.php',
        '197f91b90ff50d598ea003293247f7d2' => __DIR__ . '/../../..' . '/include/func/func.payment.php',
        '6429a7127e4af112a87ff616b7363a2d' => __DIR__ . '/../../..' . '/include/func/func.product.php',
        '75a899c82c09f4c6815a5ab473c6691e' => __DIR__ . '/../../..' . '/include/func/func.product_feeds.php',
        'd9eb0d5fec929766b1eaa87d846a00b6' => __DIR__ . '/../../..' . '/include/func/func.snapshots.php',
        '958783f5a2a344d8c8bc789f72d27479' => __DIR__ . '/../../..' . '/include/func/func.taxes.php',
        '69094f3c2fec7461e41a47629a2de28d' => __DIR__ . '/../../..' . '/include/func/func.templater.php',
        '1bb638beed06175065baa2bc4f63664f' => __DIR__ . '/../../..' . '/include/func/func.tests.php',
        '5b62f9c3da43101dc7118a6037304d31' => __DIR__ . '/../../..' . '/include/func/func.user.php',
        '21d3e9b4840c61de5fb4b983afb6405d' => __DIR__ . '/../../..' . '/include/func/func.xml.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'X' => 
        array (
            'Xcart\\External_Product_Verification\\' => 36,
            'Xcart\\External_Marketplaces\\' => 28,
            'Xcart\\' => 6,
        ),
        'U' => 
        array (
            'Ups\\' => 4,
        ),
        'R' => 
        array (
            'React\\Promise\\' => 14,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Cache\\' => 10,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
            'Modules\\' => 8,
            'Mindy\\QueryBuilder\\' => 19,
        ),
        'J' => 
        array (
            'Jaybizzle\\CrawlerDetect\\' => 24,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Ring\\' => 16,
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\' => 11,
            'Google\\Auth\\' => 12,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Cache\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'Xcart\\External_Product_Verification\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/modules/External_Product_Verification/include',
        ),
        'Xcart\\External_Marketplaces\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/modules/External_Marketplaces/include',
        ),
        'Xcart\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/include/Xcart',
        ),
        'Ups\\' => 
        array (
            0 => __DIR__ . '/..' . '/gabrielbull/ups-api/src/Ups',
        ),
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Modules\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Modules',
        ),
        'Mindy\\QueryBuilder\\' => 
        array (
            0 => __DIR__ . '/..' . '/mindy/query_builder/src',
        ),
        'Jaybizzle\\CrawlerDetect\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaybizzle/crawler-detect/src',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Ring\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/ringphp/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/auth/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
        'G' => 
        array (
            'Google_Service_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient-services/src',
            ),
            'Google_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient/src',
            ),
        ),
        'F' => 
        array (
            'Fenom\\' => 
            array (
                0 => __DIR__ . '/..' . '/fenom/fenom/src',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Inflector\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/inflector/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
            'Doctrine\\Common\\Annotations\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/annotations/lib',
            ),
            'Doctrine\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/common/lib',
            ),
        ),
    );

    public static $classMap = array (
        'FBAInventoryServiceMWS_Client' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Client.php',
        'FBAInventoryServiceMWS_Exception' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Exception.php',
        'FBAInventoryServiceMWS_Interface' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Interface.php',
        'FBAInventoryServiceMWS_Mock' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Mock.php',
        'FBAInventoryServiceMWS_Model' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/GetServiceStatusResult.php',
        'FBAInventoryServiceMWS_Model_InventorySupply' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/InventorySupply.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyDetail' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/InventorySupplyDetail.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyDetailList' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/InventorySupplyDetailList.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyList' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/InventorySupplyList.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenRequest' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenRequest.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenResponse' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenResponse.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenResult' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenResult.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyRequest' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ListInventorySupplyRequest.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyResponse' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ListInventorySupplyResponse.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyResult' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ListInventorySupplyResult.php',
        'FBAInventoryServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAInventoryServiceMWS_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/ResponseMetadata.php',
        'FBAInventoryServiceMWS_Model_SellerSkuList' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/SellerSkuList.php',
        'FBAInventoryServiceMWS_Model_Timepoint' => __DIR__ . '/../../..' . '/FBAInventoryServiceMWS/Model/Timepoint.php',
        'FBAOutboundServiceMWS_Client' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Client.php',
        'FBAOutboundServiceMWS_Exception' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Exception.php',
        'FBAOutboundServiceMWS_Interface' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Interface.php',
        'FBAOutboundServiceMWS_Mock' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Mock.php',
        'FBAOutboundServiceMWS_Model' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model.php',
        'FBAOutboundServiceMWS_Model_Address' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Address.php',
        'FBAOutboundServiceMWS_Model_CODSettings' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CODSettings.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_Currency' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Currency.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindow' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/DeliveryWindow.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindowList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/DeliveryWindowList.php',
        'FBAOutboundServiceMWS_Model_Fee' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Fee.php',
        'FBAOutboundServiceMWS_Model_FeeList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FeeList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentMethodList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentMethodList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrder' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrder.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrderList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreview' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreview.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipment' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipmentList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipment' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackage' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackage.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackageList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackageList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResult.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResult.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsRequest.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResponse.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResult.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetServiceStatusResult.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResult.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResult.php',
        'FBAOutboundServiceMWS_Model_NotificationEmailList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/NotificationEmailList.php',
        'FBAOutboundServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAOutboundServiceMWS_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ResponseMetadata.php',
        'FBAOutboundServiceMWS_Model_ScheduledDeliveryInfo' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ScheduledDeliveryInfo.php',
        'FBAOutboundServiceMWS_Model_ShippingSpeedCategoryList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ShippingSpeedCategoryList.php',
        'FBAOutboundServiceMWS_Model_StringList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/StringList.php',
        'FBAOutboundServiceMWS_Model_TrackingAddress' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/TrackingAddress.php',
        'FBAOutboundServiceMWS_Model_TrackingEvent' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/TrackingEvent.php',
        'FBAOutboundServiceMWS_Model_TrackingEventList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/TrackingEventList.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItem.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_Weight' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Weight.php',
        'Fenom' => __DIR__ . '/..' . '/fenom/fenom/src/Fenom.php',
        'Google\\Auth\\ApplicationDefaultCredentials' => __DIR__ . '/..' . '/google/auth/src/ApplicationDefaultCredentials.php',
        'Google\\Auth\\CacheTrait' => __DIR__ . '/..' . '/google/auth/src/CacheTrait.php',
        'Google\\Auth\\Cache\\InvalidArgumentException' => __DIR__ . '/..' . '/google/auth/src/Cache/InvalidArgumentException.php',
        'Google\\Auth\\Cache\\Item' => __DIR__ . '/..' . '/google/auth/src/Cache/Item.php',
        'Google\\Auth\\Cache\\MemoryCacheItemPool' => __DIR__ . '/..' . '/google/auth/src/Cache/MemoryCacheItemPool.php',
        'Google\\Auth\\CredentialsLoader' => __DIR__ . '/..' . '/google/auth/src/CredentialsLoader.php',
        'Google\\Auth\\Credentials\\AppIdentityCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/AppIdentityCredentials.php',
        'Google\\Auth\\Credentials\\GCECredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/GCECredentials.php',
        'Google\\Auth\\Credentials\\IAMCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/IAMCredentials.php',
        'Google\\Auth\\Credentials\\ServiceAccountCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/ServiceAccountCredentials.php',
        'Google\\Auth\\Credentials\\ServiceAccountJwtAccessCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/ServiceAccountJwtAccessCredentials.php',
        'Google\\Auth\\Credentials\\UserRefreshCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/UserRefreshCredentials.php',
        'Google\\Auth\\FetchAuthTokenCache' => __DIR__ . '/..' . '/google/auth/src/FetchAuthTokenCache.php',
        'Google\\Auth\\FetchAuthTokenInterface' => __DIR__ . '/..' . '/google/auth/src/FetchAuthTokenInterface.php',
        'Google\\Auth\\HttpHandler\\Guzzle5HttpHandler' => __DIR__ . '/..' . '/google/auth/src/HttpHandler/Guzzle5HttpHandler.php',
        'Google\\Auth\\HttpHandler\\Guzzle6HttpHandler' => __DIR__ . '/..' . '/google/auth/src/HttpHandler/Guzzle6HttpHandler.php',
        'Google\\Auth\\HttpHandler\\HttpHandlerFactory' => __DIR__ . '/..' . '/google/auth/src/HttpHandler/HttpHandlerFactory.php',
        'Google\\Auth\\Middleware\\AuthTokenMiddleware' => __DIR__ . '/..' . '/google/auth/src/Middleware/AuthTokenMiddleware.php',
        'Google\\Auth\\Middleware\\ScopedAccessTokenMiddleware' => __DIR__ . '/..' . '/google/auth/src/Middleware/ScopedAccessTokenMiddleware.php',
        'Google\\Auth\\Middleware\\SimpleMiddleware' => __DIR__ . '/..' . '/google/auth/src/Middleware/SimpleMiddleware.php',
        'Google\\Auth\\OAuth2' => __DIR__ . '/..' . '/google/auth/src/OAuth2.php',
        'Google\\Auth\\Subscriber\\AuthTokenSubscriber' => __DIR__ . '/..' . '/google/auth/src/Subscriber/AuthTokenSubscriber.php',
        'Google\\Auth\\Subscriber\\ScopedAccessTokenSubscriber' => __DIR__ . '/..' . '/google/auth/src/Subscriber/ScopedAccessTokenSubscriber.php',
        'Google\\Auth\\Subscriber\\SimpleSubscriber' => __DIR__ . '/..' . '/google/auth/src/Subscriber/SimpleSubscriber.php',
        'Google_Service_Exception' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Exception.php',
        'Google_Service_Resource' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Resource.php',
        'MarketplaceWebServiceOrders_Client' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Client.php',
        'MarketplaceWebServiceOrders_Exception' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Exception.php',
        'MarketplaceWebServiceOrders_Interface' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Interface.php',
        'MarketplaceWebServiceOrders_Mock' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Mock.php',
        'MarketplaceWebServiceOrders_Model' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model.php',
        'MarketplaceWebServiceOrders_Model_Address' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/Address.php',
        'MarketplaceWebServiceOrders_Model_GetOrderRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/GetOrderRequest.php',
        'MarketplaceWebServiceOrders_Model_GetOrderResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/GetOrderResponse.php',
        'MarketplaceWebServiceOrders_Model_GetOrderResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/GetOrderResult.php',
        'MarketplaceWebServiceOrders_Model_GetServiceStatusRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/GetServiceStatusRequest.php',
        'MarketplaceWebServiceOrders_Model_GetServiceStatusResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/GetServiceStatusResponse.php',
        'MarketplaceWebServiceOrders_Model_GetServiceStatusResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/GetServiceStatusResult.php',
        'MarketplaceWebServiceOrders_Model_InvoiceData' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/InvoiceData.php',
        'MarketplaceWebServiceOrders_Model_ListOrderItemsByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrderItemsByNextTokenRequest.php',
        'MarketplaceWebServiceOrders_Model_ListOrderItemsByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrderItemsByNextTokenResponse.php',
        'MarketplaceWebServiceOrders_Model_ListOrderItemsByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrderItemsByNextTokenResult.php',
        'MarketplaceWebServiceOrders_Model_ListOrderItemsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrderItemsRequest.php',
        'MarketplaceWebServiceOrders_Model_ListOrderItemsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrderItemsResponse.php',
        'MarketplaceWebServiceOrders_Model_ListOrderItemsResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrderItemsResult.php',
        'MarketplaceWebServiceOrders_Model_ListOrdersByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrdersByNextTokenRequest.php',
        'MarketplaceWebServiceOrders_Model_ListOrdersByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrdersByNextTokenResponse.php',
        'MarketplaceWebServiceOrders_Model_ListOrdersByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrdersByNextTokenResult.php',
        'MarketplaceWebServiceOrders_Model_ListOrdersRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrdersRequest.php',
        'MarketplaceWebServiceOrders_Model_ListOrdersResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrdersResponse.php',
        'MarketplaceWebServiceOrders_Model_ListOrdersResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ListOrdersResult.php',
        'MarketplaceWebServiceOrders_Model_Message' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/Message.php',
        'MarketplaceWebServiceOrders_Model_Money' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/Money.php',
        'MarketplaceWebServiceOrders_Model_Order' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/Order.php',
        'MarketplaceWebServiceOrders_Model_OrderItem' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/OrderItem.php',
        'MarketplaceWebServiceOrders_Model_PaymentExecutionDetailItem' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/PaymentExecutionDetailItem.php',
        'MarketplaceWebServiceOrders_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ResponseHeaderMetadata.php',
        'MarketplaceWebServiceOrders_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebServiceOrders/Model/ResponseMetadata.php',
        'MarketplaceWebServiceProducts_Client' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Client.php',
        'MarketplaceWebServiceProducts_Exception' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Exception.php',
        'MarketplaceWebServiceProducts_Interface' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Interface.php',
        'MarketplaceWebServiceProducts_Mock' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Mock.php',
        'MarketplaceWebServiceProducts_Model' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model.php',
        'MarketplaceWebServiceProducts_Model_ASINIdentifier' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ASINIdentifier.php',
        'MarketplaceWebServiceProducts_Model_ASINListType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ASINListType.php',
        'MarketplaceWebServiceProducts_Model_AttributeSetList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/AttributeSetList.php',
        'MarketplaceWebServiceProducts_Model_Categories' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/Categories.php',
        'MarketplaceWebServiceProducts_Model_CompetitivePriceList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/CompetitivePriceList.php',
        'MarketplaceWebServiceProducts_Model_CompetitivePriceType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/CompetitivePriceType.php',
        'MarketplaceWebServiceProducts_Model_CompetitivePricingType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/CompetitivePricingType.php',
        'MarketplaceWebServiceProducts_Model_Error' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/Error.php',
        'MarketplaceWebServiceProducts_Model_ErrorDetail' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ErrorDetail.php',
        'MarketplaceWebServiceProducts_Model_GetCompetitivePricingForASINRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetCompetitivePricingForASINRequest.php',
        'MarketplaceWebServiceProducts_Model_GetCompetitivePricingForASINResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetCompetitivePricingForASINResponse.php',
        'MarketplaceWebServiceProducts_Model_GetCompetitivePricingForASINResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetCompetitivePricingForASINResult.php',
        'MarketplaceWebServiceProducts_Model_GetCompetitivePricingForSKURequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetCompetitivePricingForSKURequest.php',
        'MarketplaceWebServiceProducts_Model_GetCompetitivePricingForSKUResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetCompetitivePricingForSKUResponse.php',
        'MarketplaceWebServiceProducts_Model_GetCompetitivePricingForSKUResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetCompetitivePricingForSKUResult.php',
        'MarketplaceWebServiceProducts_Model_GetLowestOfferListingsForASINRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetLowestOfferListingsForASINRequest.php',
        'MarketplaceWebServiceProducts_Model_GetLowestOfferListingsForASINResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetLowestOfferListingsForASINResponse.php',
        'MarketplaceWebServiceProducts_Model_GetLowestOfferListingsForASINResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetLowestOfferListingsForASINResult.php',
        'MarketplaceWebServiceProducts_Model_GetLowestOfferListingsForSKURequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetLowestOfferListingsForSKURequest.php',
        'MarketplaceWebServiceProducts_Model_GetLowestOfferListingsForSKUResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetLowestOfferListingsForSKUResponse.php',
        'MarketplaceWebServiceProducts_Model_GetLowestOfferListingsForSKUResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetLowestOfferListingsForSKUResult.php',
        'MarketplaceWebServiceProducts_Model_GetMatchingProductForIdRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMatchingProductForIdRequest.php',
        'MarketplaceWebServiceProducts_Model_GetMatchingProductForIdResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMatchingProductForIdResponse.php',
        'MarketplaceWebServiceProducts_Model_GetMatchingProductForIdResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMatchingProductForIdResult.php',
        'MarketplaceWebServiceProducts_Model_GetMatchingProductRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMatchingProductRequest.php',
        'MarketplaceWebServiceProducts_Model_GetMatchingProductResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMatchingProductResponse.php',
        'MarketplaceWebServiceProducts_Model_GetMatchingProductResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMatchingProductResult.php',
        'MarketplaceWebServiceProducts_Model_GetMyPriceForASINRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMyPriceForASINRequest.php',
        'MarketplaceWebServiceProducts_Model_GetMyPriceForASINResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMyPriceForASINResponse.php',
        'MarketplaceWebServiceProducts_Model_GetMyPriceForASINResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMyPriceForASINResult.php',
        'MarketplaceWebServiceProducts_Model_GetMyPriceForSKURequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMyPriceForSKURequest.php',
        'MarketplaceWebServiceProducts_Model_GetMyPriceForSKUResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMyPriceForSKUResponse.php',
        'MarketplaceWebServiceProducts_Model_GetMyPriceForSKUResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetMyPriceForSKUResult.php',
        'MarketplaceWebServiceProducts_Model_GetProductCategoriesForASINRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetProductCategoriesForASINRequest.php',
        'MarketplaceWebServiceProducts_Model_GetProductCategoriesForASINResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetProductCategoriesForASINResponse.php',
        'MarketplaceWebServiceProducts_Model_GetProductCategoriesForASINResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetProductCategoriesForASINResult.php',
        'MarketplaceWebServiceProducts_Model_GetProductCategoriesForSKURequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetProductCategoriesForSKURequest.php',
        'MarketplaceWebServiceProducts_Model_GetProductCategoriesForSKUResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetProductCategoriesForSKUResponse.php',
        'MarketplaceWebServiceProducts_Model_GetProductCategoriesForSKUResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetProductCategoriesForSKUResult.php',
        'MarketplaceWebServiceProducts_Model_GetServiceStatusRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetServiceStatusRequest.php',
        'MarketplaceWebServiceProducts_Model_GetServiceStatusResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetServiceStatusResponse.php',
        'MarketplaceWebServiceProducts_Model_GetServiceStatusResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/GetServiceStatusResult.php',
        'MarketplaceWebServiceProducts_Model_IdListType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/IdListType.php',
        'MarketplaceWebServiceProducts_Model_IdentifierType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/IdentifierType.php',
        'MarketplaceWebServiceProducts_Model_ListMatchingProductsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ListMatchingProductsRequest.php',
        'MarketplaceWebServiceProducts_Model_ListMatchingProductsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ListMatchingProductsResponse.php',
        'MarketplaceWebServiceProducts_Model_ListMatchingProductsResult' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ListMatchingProductsResult.php',
        'MarketplaceWebServiceProducts_Model_LowestOfferListingList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/LowestOfferListingList.php',
        'MarketplaceWebServiceProducts_Model_LowestOfferListingType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/LowestOfferListingType.php',
        'MarketplaceWebServiceProducts_Model_Message' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/Message.php',
        'MarketplaceWebServiceProducts_Model_MessageList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/MessageList.php',
        'MarketplaceWebServiceProducts_Model_MoneyType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/MoneyType.php',
        'MarketplaceWebServiceProducts_Model_NumberOfOfferListingsList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/NumberOfOfferListingsList.php',
        'MarketplaceWebServiceProducts_Model_OfferListingCountType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/OfferListingCountType.php',
        'MarketplaceWebServiceProducts_Model_OfferType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/OfferType.php',
        'MarketplaceWebServiceProducts_Model_OffersList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/OffersList.php',
        'MarketplaceWebServiceProducts_Model_Points' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/Points.php',
        'MarketplaceWebServiceProducts_Model_PriceType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/PriceType.php',
        'MarketplaceWebServiceProducts_Model_Product' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/Product.php',
        'MarketplaceWebServiceProducts_Model_ProductList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ProductList.php',
        'MarketplaceWebServiceProducts_Model_QualifiersType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/QualifiersType.php',
        'MarketplaceWebServiceProducts_Model_RelationshipList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/RelationshipList.php',
        'MarketplaceWebServiceProducts_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ResponseHeaderMetadata.php',
        'MarketplaceWebServiceProducts_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ResponseMetadata.php',
        'MarketplaceWebServiceProducts_Model_SalesRankList' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/SalesRankList.php',
        'MarketplaceWebServiceProducts_Model_SalesRankType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/SalesRankType.php',
        'MarketplaceWebServiceProducts_Model_SellerSKUIdentifier' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/SellerSKUIdentifier.php',
        'MarketplaceWebServiceProducts_Model_SellerSKUListType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/SellerSKUListType.php',
        'MarketplaceWebServiceProducts_Model_ShippingTimeType' => __DIR__ . '/../../..' . '/MarketplaceWebServiceProducts/Model/ShippingTimeType.php',
        'MarketplaceWebService_Client' => __DIR__ . '/../../..' . '/MarketplaceWebService/Client.php',
        'MarketplaceWebService_Exception' => __DIR__ . '/../../..' . '/MarketplaceWebService/Exception.php',
        'MarketplaceWebService_Interface' => __DIR__ . '/../../..' . '/MarketplaceWebService/Interface.php',
        'MarketplaceWebService_Mock' => __DIR__ . '/../../..' . '/MarketplaceWebService/Mock.php',
        'MarketplaceWebService_Model' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelFeedSubmissionsRequest.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelFeedSubmissionsResponse.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelFeedSubmissionsResult.php',
        'MarketplaceWebService_Model_CancelReportRequestsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelReportRequestsRequest.php',
        'MarketplaceWebService_Model_CancelReportRequestsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelReportRequestsResponse.php',
        'MarketplaceWebService_Model_CancelReportRequestsResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelReportRequestsResult.php',
        'MarketplaceWebService_Model_ContentType' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ContentType.php',
        'MarketplaceWebService_Model_Error' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/Error.php',
        'MarketplaceWebService_Model_ErrorResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ErrorResponse.php',
        'MarketplaceWebService_Model_FeedSubmissionInfo' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/FeedSubmissionInfo.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionCountRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionCountResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionCountResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionResultRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionResultResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionResultResult.php',
        'MarketplaceWebService_Model_GetReportCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportCountRequest.php',
        'MarketplaceWebService_Model_GetReportCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportCountResponse.php',
        'MarketplaceWebService_Model_GetReportCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportCountResult.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListRequest.php',
        'MarketplaceWebService_Model_GetReportListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListResponse.php',
        'MarketplaceWebService_Model_GetReportListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListResult.php',
        'MarketplaceWebService_Model_GetReportRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestCountRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestCountResponse.php',
        'MarketplaceWebService_Model_GetReportRequestCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestCountResult.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportRequestListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListResult.php',
        'MarketplaceWebService_Model_GetReportResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportResponse.php',
        'MarketplaceWebService_Model_GetReportResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportResult.php',
        'MarketplaceWebService_Model_GetReportScheduleCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleCountRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleCountResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleCountResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListResult.php',
        'MarketplaceWebService_Model_IdList' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/IdList.php',
        'MarketplaceWebService_Model_ManageReportScheduleRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ManageReportScheduleRequest.php',
        'MarketplaceWebService_Model_ManageReportScheduleResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ManageReportScheduleResponse.php',
        'MarketplaceWebService_Model_ManageReportScheduleResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ManageReportScheduleResult.php',
        'MarketplaceWebService_Model_ReportInfo' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ReportInfo.php',
        'MarketplaceWebService_Model_ReportRequestInfo' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ReportRequestInfo.php',
        'MarketplaceWebService_Model_ReportSchedule' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ReportSchedule.php',
        'MarketplaceWebService_Model_RequestReportRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/RequestReportRequest.php',
        'MarketplaceWebService_Model_RequestReportResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/RequestReportResponse.php',
        'MarketplaceWebService_Model_RequestReportResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/RequestReportResult.php',
        'MarketplaceWebService_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ResponseHeaderMetadata.php',
        'MarketplaceWebService_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ResponseMetadata.php',
        'MarketplaceWebService_Model_StatusList' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/StatusList.php',
        'MarketplaceWebService_Model_SubmitFeedRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/SubmitFeedRequest.php',
        'MarketplaceWebService_Model_SubmitFeedResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/SubmitFeedResponse.php',
        'MarketplaceWebService_Model_SubmitFeedResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/SubmitFeedResult.php',
        'MarketplaceWebService_Model_TypeList' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/TypeList.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/UpdateReportAcknowledgementsRequest.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/UpdateReportAcknowledgementsResponse.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/UpdateReportAcknowledgementsResult.php',
        'RequestType' => __DIR__ . '/../../..' . '/MarketplaceWebService/RequestType.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixesPsr0;
            $loader->classMap = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$classMap;

        }, null, ClassLoader::class);
    }
}
