<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit861ac975f6d25dbefdaa211ac60e8f2f
{
    public static $files = array (
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'X' => 
        array (
            'Xcart\\External_Product_Verification\\' => 36,
            'Xcart\\External_MarketPlace\\' => 27,
            'Xcart\\' => 6,
        ),
        'R' => 
        array (
            'React\\Promise\\' => 14,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Cache\\' => 10,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Ring\\' => 16,
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\' => 11,
            'Google\\Auth\\' => 12,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'Xcart\\External_Product_Verification\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/modules/External_Product_Verification/include',
        ),
        'Xcart\\External_MarketPlace\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/modules/External_Marketplaces/include',
        ),
        'Xcart\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/include/Xcart',
        ),
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Ring\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/ringphp/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/auth/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'G' => 
        array (
            'Google_Service_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient-services/src',
            ),
            'Google_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient/src',
            ),
        ),
    );

    public static $classMap = array (
        'FBAOutboundServiceMWS_Client' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Client.php',
        'FBAOutboundServiceMWS_Exception' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Exception.php',
        'FBAOutboundServiceMWS_Interface' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Interface.php',
        'FBAOutboundServiceMWS_Mock' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Mock.php',
        'FBAOutboundServiceMWS_Model' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model.php',
        'FBAOutboundServiceMWS_Model_Address' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Address.php',
        'FBAOutboundServiceMWS_Model_CODSettings' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CODSettings.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_Currency' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Currency.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindow' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/DeliveryWindow.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindowList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/DeliveryWindowList.php',
        'FBAOutboundServiceMWS_Model_Fee' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Fee.php',
        'FBAOutboundServiceMWS_Model_FeeList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FeeList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentMethodList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentMethodList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrder' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrder.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentOrderList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreview' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreview.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipment' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipmentList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipment' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackage' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackage.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackageList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackageList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResult.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResult.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsRequest.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResponse.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResult.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/GetServiceStatusResult.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResult.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResult' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResult.php',
        'FBAOutboundServiceMWS_Model_NotificationEmailList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/NotificationEmailList.php',
        'FBAOutboundServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAOutboundServiceMWS_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ResponseMetadata.php',
        'FBAOutboundServiceMWS_Model_ScheduledDeliveryInfo' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ScheduledDeliveryInfo.php',
        'FBAOutboundServiceMWS_Model_ShippingSpeedCategoryList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/ShippingSpeedCategoryList.php',
        'FBAOutboundServiceMWS_Model_StringList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/StringList.php',
        'FBAOutboundServiceMWS_Model_TrackingAddress' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/TrackingAddress.php',
        'FBAOutboundServiceMWS_Model_TrackingEvent' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/TrackingEvent.php',
        'FBAOutboundServiceMWS_Model_TrackingEventList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/TrackingEventList.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItem.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItem' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItemList' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderRequest' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderResponse' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_Weight' => __DIR__ . '/../../..' . '/src/FBAOutboundServiceMWS/Model/Weight.php',
        'Google\\Auth\\ApplicationDefaultCredentials' => __DIR__ . '/..' . '/google/auth/src/ApplicationDefaultCredentials.php',
        'Google\\Auth\\CacheTrait' => __DIR__ . '/..' . '/google/auth/src/CacheTrait.php',
        'Google\\Auth\\Cache\\InvalidArgumentException' => __DIR__ . '/..' . '/google/auth/src/Cache/InvalidArgumentException.php',
        'Google\\Auth\\Cache\\Item' => __DIR__ . '/..' . '/google/auth/src/Cache/Item.php',
        'Google\\Auth\\Cache\\MemoryCacheItemPool' => __DIR__ . '/..' . '/google/auth/src/Cache/MemoryCacheItemPool.php',
        'Google\\Auth\\CredentialsLoader' => __DIR__ . '/..' . '/google/auth/src/CredentialsLoader.php',
        'Google\\Auth\\Credentials\\AppIdentityCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/AppIdentityCredentials.php',
        'Google\\Auth\\Credentials\\GCECredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/GCECredentials.php',
        'Google\\Auth\\Credentials\\IAMCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/IAMCredentials.php',
        'Google\\Auth\\Credentials\\ServiceAccountCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/ServiceAccountCredentials.php',
        'Google\\Auth\\Credentials\\ServiceAccountJwtAccessCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/ServiceAccountJwtAccessCredentials.php',
        'Google\\Auth\\Credentials\\UserRefreshCredentials' => __DIR__ . '/..' . '/google/auth/src/Credentials/UserRefreshCredentials.php',
        'Google\\Auth\\FetchAuthTokenCache' => __DIR__ . '/..' . '/google/auth/src/FetchAuthTokenCache.php',
        'Google\\Auth\\FetchAuthTokenInterface' => __DIR__ . '/..' . '/google/auth/src/FetchAuthTokenInterface.php',
        'Google\\Auth\\HttpHandler\\Guzzle5HttpHandler' => __DIR__ . '/..' . '/google/auth/src/HttpHandler/Guzzle5HttpHandler.php',
        'Google\\Auth\\HttpHandler\\Guzzle6HttpHandler' => __DIR__ . '/..' . '/google/auth/src/HttpHandler/Guzzle6HttpHandler.php',
        'Google\\Auth\\HttpHandler\\HttpHandlerFactory' => __DIR__ . '/..' . '/google/auth/src/HttpHandler/HttpHandlerFactory.php',
        'Google\\Auth\\Middleware\\AuthTokenMiddleware' => __DIR__ . '/..' . '/google/auth/src/Middleware/AuthTokenMiddleware.php',
        'Google\\Auth\\Middleware\\ScopedAccessTokenMiddleware' => __DIR__ . '/..' . '/google/auth/src/Middleware/ScopedAccessTokenMiddleware.php',
        'Google\\Auth\\Middleware\\SimpleMiddleware' => __DIR__ . '/..' . '/google/auth/src/Middleware/SimpleMiddleware.php',
        'Google\\Auth\\OAuth2' => __DIR__ . '/..' . '/google/auth/src/OAuth2.php',
        'Google\\Auth\\Subscriber\\AuthTokenSubscriber' => __DIR__ . '/..' . '/google/auth/src/Subscriber/AuthTokenSubscriber.php',
        'Google\\Auth\\Subscriber\\ScopedAccessTokenSubscriber' => __DIR__ . '/..' . '/google/auth/src/Subscriber/ScopedAccessTokenSubscriber.php',
        'Google\\Auth\\Subscriber\\SimpleSubscriber' => __DIR__ . '/..' . '/google/auth/src/Subscriber/SimpleSubscriber.php',
        'Google_Service_Exception' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Exception.php',
        'Google_Service_Resource' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Resource.php',
        'MarketplaceWebService_Client' => __DIR__ . '/../../..' . '/MarketplaceWebService/Client.php',
        'MarketplaceWebService_Exception' => __DIR__ . '/../../..' . '/MarketplaceWebService/Exception.php',
        'MarketplaceWebService_Interface' => __DIR__ . '/../../..' . '/MarketplaceWebService/Interface.php',
        'MarketplaceWebService_Mock' => __DIR__ . '/../../..' . '/MarketplaceWebService/Mock.php',
        'MarketplaceWebService_Model' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelFeedSubmissionsRequest.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelFeedSubmissionsResponse.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelFeedSubmissionsResult.php',
        'MarketplaceWebService_Model_CancelReportRequestsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelReportRequestsRequest.php',
        'MarketplaceWebService_Model_CancelReportRequestsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelReportRequestsResponse.php',
        'MarketplaceWebService_Model_CancelReportRequestsResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/CancelReportRequestsResult.php',
        'MarketplaceWebService_Model_ContentType' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ContentType.php',
        'MarketplaceWebService_Model_Error' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/Error.php',
        'MarketplaceWebService_Model_ErrorResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ErrorResponse.php',
        'MarketplaceWebService_Model_FeedSubmissionInfo' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/FeedSubmissionInfo.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionCountRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionCountResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionCountResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionListResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionResultRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionResultResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetFeedSubmissionResultResult.php',
        'MarketplaceWebService_Model_GetReportCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportCountRequest.php',
        'MarketplaceWebService_Model_GetReportCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportCountResponse.php',
        'MarketplaceWebService_Model_GetReportCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportCountResult.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListRequest.php',
        'MarketplaceWebService_Model_GetReportListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListResponse.php',
        'MarketplaceWebService_Model_GetReportListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportListResult.php',
        'MarketplaceWebService_Model_GetReportRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestCountRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestCountResponse.php',
        'MarketplaceWebService_Model_GetReportRequestCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestCountResult.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportRequestListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportRequestListResult.php',
        'MarketplaceWebService_Model_GetReportResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportResponse.php',
        'MarketplaceWebService_Model_GetReportResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportResult.php',
        'MarketplaceWebService_Model_GetReportScheduleCountRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleCountRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleCountResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleCountResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/GetReportScheduleListResult.php',
        'MarketplaceWebService_Model_IdList' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/IdList.php',
        'MarketplaceWebService_Model_ManageReportScheduleRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ManageReportScheduleRequest.php',
        'MarketplaceWebService_Model_ManageReportScheduleResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ManageReportScheduleResponse.php',
        'MarketplaceWebService_Model_ManageReportScheduleResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ManageReportScheduleResult.php',
        'MarketplaceWebService_Model_ReportInfo' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ReportInfo.php',
        'MarketplaceWebService_Model_ReportRequestInfo' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ReportRequestInfo.php',
        'MarketplaceWebService_Model_ReportSchedule' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ReportSchedule.php',
        'MarketplaceWebService_Model_RequestReportRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/RequestReportRequest.php',
        'MarketplaceWebService_Model_RequestReportResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/RequestReportResponse.php',
        'MarketplaceWebService_Model_RequestReportResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/RequestReportResult.php',
        'MarketplaceWebService_Model_ResponseHeaderMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ResponseHeaderMetadata.php',
        'MarketplaceWebService_Model_ResponseMetadata' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/ResponseMetadata.php',
        'MarketplaceWebService_Model_StatusList' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/StatusList.php',
        'MarketplaceWebService_Model_SubmitFeedRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/SubmitFeedRequest.php',
        'MarketplaceWebService_Model_SubmitFeedResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/SubmitFeedResponse.php',
        'MarketplaceWebService_Model_SubmitFeedResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/SubmitFeedResult.php',
        'MarketplaceWebService_Model_TypeList' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/TypeList.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsRequest' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/UpdateReportAcknowledgementsRequest.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResponse' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/UpdateReportAcknowledgementsResponse.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResult' => __DIR__ . '/../../..' . '/MarketplaceWebService/Model/UpdateReportAcknowledgementsResult.php',
        'RequestType' => __DIR__ . '/../../..' . '/MarketplaceWebService/RequestType.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit861ac975f6d25dbefdaa211ac60e8f2f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit861ac975f6d25dbefdaa211ac60e8f2f::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit861ac975f6d25dbefdaa211ac60e8f2f::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit861ac975f6d25dbefdaa211ac60e8f2f::$classMap;

        }, null, ClassLoader::class);
    }
}
