<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'ad155f8f1cf0d418fe49e248db8c661b' => $vendorDir . '/react/promise/src/functions_include.php',
    'a0edc8309cc5e1d60e3047b5df6b7052' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    'decc78cc4436b1292c6c0d151b19445c' => $vendorDir . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    '68f9084e889ebf718663435970ab45e3' => $vendorDir . '/mindy/query_builder/src/Conditions.php',
    '38aa9ffa312700065ceed8bf7bcb7a53' => $baseDir . '/include/func/func.core.php',
    'f550ebde9e69876a00625883277835ce' => $baseDir . '/include/func/func.amazon.php',
    'dca41d7b610d234855ab845f35115f14' => $baseDir . '/include/func/func.amazon_shipping.php',
    'c074bc0f3f52cf1c23cb50d0b4b45a7d' => $baseDir . '/include/func/func.backoffice.php',
    'c735e56e84931684b20d9a61359574fb' => $baseDir . '/include/func/func.cart.php',
    '4fe8cfc3c08ff324bbca0dc5a2183eb2' => $baseDir . '/include/func/func.category.php',
    '7a0f7bab0b4c07a48efbd41ed882e12c' => $baseDir . '/include/func/func.clean_urls.php',
    '2e533e5cb2c07d8428158b9e0b1a8f59' => $baseDir . '/include/func/func.crypt.php',
    '77051ec6f375af33ee9a9812c74448bf' => $baseDir . '/include/func/func.db.php',
    '1f6b825d735402a45f92496cd075653e' => $baseDir . '/include/func/func.debug.php',
    '697d63fd5a525232af8e966a1be1059c' => $baseDir . '/include/func/func.export.php',
    '4adcbdf83ad97c61a32666548447b10e' => $baseDir . '/include/func/func.files.php',
    'ac35a74c3508918853d2004669f1c05a' => $baseDir . '/include/func/func.fraud.php',
    '4f893e9c6a947e25f96c5e139bc5cf3d' => $baseDir . '/include/func/func.froogle.php',
    'a98b2562f5334952ccc83cd6c2b0cbd3' => $baseDir . '/include/func/func.gd.php',
    'd324cee2ece3cf9e5f2322d42cfdff38' => $baseDir . '/include/func/func.http.php',
    'dc42f8b8545788e38401347f9114ea93' => $baseDir . '/include/func/func.https_curl.php',
    '631dd34c8ce264611ac30d6287265ec0' => $baseDir . '/include/func/func.https_httpscli.php',
    'a33f592b4c44fb72c8360271220c4c4b' => $baseDir . '/include/func/func.https_libcurl.php',
    'e253c01efb77a61fbfc0519e877f00e9' => $baseDir . '/include/func/func.https_openssl.php',
    'add00bd7c7e925fa77868dfaf674a32d' => $baseDir . '/include/func/func.https_ssleay.php',
    '5f8e7042a87b85cfc6f2ef727b7894fa' => $baseDir . '/include/func/func.image.php',
    'e795ed7bab7715b7597022371a62c8f9' => $baseDir . '/include/func/func.import.php',
    '83b744f1987ac050e1aa79e9dfd286b4' => $baseDir . '/include/func/func.mail.php',
    '96fe48a4cf0e8647d8aa17a0e134b8a0' => $baseDir . '/include/func/func.order.php',
    '49c17c188cf012fc294a8bf1c3848a8d' => $baseDir . '/include/func/func.order_edit.php',
    '197f91b90ff50d598ea003293247f7d2' => $baseDir . '/include/func/func.payment.php',
    '6429a7127e4af112a87ff616b7363a2d' => $baseDir . '/include/func/func.product.php',
    '75a899c82c09f4c6815a5ab473c6691e' => $baseDir . '/include/func/func.product_feeds.php',
    'd9eb0d5fec929766b1eaa87d846a00b6' => $baseDir . '/include/func/func.snapshots.php',
    '958783f5a2a344d8c8bc789f72d27479' => $baseDir . '/include/func/func.taxes.php',
    '69094f3c2fec7461e41a47629a2de28d' => $baseDir . '/include/func/func.templater.php',
    '1bb638beed06175065baa2bc4f63664f' => $baseDir . '/include/func/func.tests.php',
    '5b62f9c3da43101dc7118a6037304d31' => $baseDir . '/include/func/func.user.php',
    '21d3e9b4840c61de5fb4b983afb6405d' => $baseDir . '/include/func/func.xml.php',
);
