<?php /* Smarty version 2.6.12, created on 2015-11-02 03:05:17
         compiled from customer/buttons/button.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'xevent', 'customer/buttons/button.tpl', 1, false),array('modifier', 'regex_replace', 'customer/buttons/button.tpl', 5, false),array('modifier', 'amp', 'customer/buttons/button.tpl', 11, false),array('modifier', 'has_string', 'customer/buttons/button.tpl', 23, false),array('modifier', 'default', 'customer/buttons/button.tpl', 29, false),array('modifier', 'strip_tags', 'customer/buttons/button.tpl', 29, false),array('modifier', 'escape', 'customer/buttons/button.tpl', 29, false),)), $this); ?>
<?php func_load_lang($this, "customer/buttons/button.tpl","lbl_close"); ?><?php if ($this->_tpl_vars['x_core_started']):  echo x_tpl_fire_event(array('name' => 'before','tpl' => "customer/buttons/button.tpl"), $this); endif;  $this->assign('js_link', ((is_array($_tmp=$this->_tpl_vars['href'])) ? $this->_run_mod_handler('regex_replace', true, $_tmp, "/^\s*javascript\s*:/Si", "") : smarty_modifier_regex_replace($_tmp, "/^\s*javascript\s*:/Si", "")));  if ($this->_tpl_vars['js_link'] == $this->_tpl_vars['href']): ?>
  <?php if ($this->_tpl_vars['href']): ?>
    <?php $this->assign('is_link', true); ?>
  <?php endif; ?>
  <?php $this->assign('js_link', false); ?>
  <?php $this->assign('href', ((is_array($_tmp=$this->_tpl_vars['href'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp)));  else: ?>
  <?php $this->assign('js_link', $this->_tpl_vars['href']); ?>
  <?php if ($this->_tpl_vars['js_to_href'] != 'Y'): ?>
    <?php $this->assign('onclick', $this->_tpl_vars['href']); ?>
    <?php if ($this->_tpl_vars['link_href']): ?>
      <?php $this->assign('href', $this->_tpl_vars['link_href']); ?>
    <?php else: ?>
      <?php $this->assign('href', "javascript:void(0);"); ?>
    <?php endif; ?>
  <?php endif;  endif;  if (! $this->_tpl_vars['data_theme'] && strpos($this->_tpl_vars['additional_button_class'], "main-button")): ?>
  <?php $this->assign('data_theme', 'b');  endif;  if ($this->_tpl_vars['style'] == 'link'): ?>
  <?php if ($this->_tpl_vars['type'] == 'input'): ?>
    <?php echo '<button type="submit" class="button';  if ($this->_tpl_vars['additional_button_class']):  echo ' ';  echo $this->_tpl_vars['additional_button_class'];  echo '';  endif;  echo '" title="';  echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp));  echo '"';  if ($this->_tpl_vars['js_link']):  echo ' onclick="';  echo $this->_tpl_vars['js_link'];  echo '"';  endif;  echo ' data-theme="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'b') : smarty_modifier_default($_tmp, 'b'));  echo '" data-inline="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true'));  echo '"';  if ($this->_tpl_vars['data_icon']):  echo ' data-icon="';  echo $this->_tpl_vars['data_icon'];  echo '" data-iconpos="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_iconpos'])) ? $this->_run_mod_handler('default', true, $_tmp, 'right') : smarty_modifier_default($_tmp, 'right'));  echo '"';  endif;  echo '';  if ($this->_tpl_vars['button_id']):  echo ' id="';  echo $this->_tpl_vars['button_id'];  echo '"';  endif;  echo ' data-mini="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false'));  echo '">';  echo ((is_array($_tmp=$this->_tpl_vars['button_title'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp));  echo '</button>'; ?>

  <?php else: ?>
    <?php echo '<a class="button';  if ($this->_tpl_vars['additional_button_class']):  echo ' ';  echo $this->_tpl_vars['additional_button_class'];  echo '';  endif;  echo '" href="';  echo ((is_array($_tmp=$this->_tpl_vars['href'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp));  echo '" ';  if ($this->_tpl_vars['onclick'] != ''):  echo ' onclick="';  echo $this->_tpl_vars['onclick'];  echo '; return false;"';  endif;  echo ' title="';  echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp));  echo '" ';  if ($this->_tpl_vars['target'] != ''):  echo ' target="';  echo $this->_tpl_vars['target'];  echo '"';  endif;  echo ' data-role="button" data-theme="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c'));  echo '" data-inline="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true'));  echo '"';  if ($this->_tpl_vars['data_icon']):  echo ' data-icon="';  echo $this->_tpl_vars['data_icon'];  echo '" data-iconpos="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_iconpos'])) ? $this->_run_mod_handler('default', true, $_tmp, 'right') : smarty_modifier_default($_tmp, 'right'));  echo '"';  endif;  echo '';  if ($this->_tpl_vars['button_id']):  echo ' id="';  echo $this->_tpl_vars['button_id'];  echo '"';  endif;  echo ' data-mini="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false'));  echo '"';  if ($this->_tpl_vars['rel_external']):  echo ' rel="external"';  endif;  echo '>';  echo ((is_array($_tmp=$this->_tpl_vars['button_title'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp));  echo '</a>'; ?>

  <?php endif;  elseif ($this->_tpl_vars['style'] == 'image'): ?>
    <?php if ($this->_tpl_vars['type'] == 'input'): ?>
    <a href="#"<?php if ($this->_tpl_vars['js_link']): ?> onclick="<?php echo $this->_tpl_vars['js_link']; ?>
"<?php endif;  if ($this->_tpl_vars['button_id']): ?> id="<?php echo ((is_array($_tmp=$this->_tpl_vars['button_id'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
"<?php endif;  if ($this->_tpl_vars['rel_external']): ?> rel="external"<?php endif; ?>><img class="button<?php if ($this->_tpl_vars['additional_button_class']): ?> <?php echo $this->_tpl_vars['additional_button_class'];  endif; ?>" src="<?php echo $this->_tpl_vars['ImagesDir']; ?>
/spacer.gif" alt="<?php echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
" /></a>
  <?php else: ?>
    <?php echo '<a class="button';  if ($this->_tpl_vars['additional_button_class']):  echo ' ';  echo $this->_tpl_vars['additional_button_class'];  echo '';  endif;  echo '" href="';  echo ((is_array($_tmp=$this->_tpl_vars['href'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp));  echo '"';  if ($this->_tpl_vars['onclick'] != ''):  echo ' onclick="';  echo $this->_tpl_vars['onclick'];  echo '"';  endif;  echo ' title="';  echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp));  echo '"';  if ($this->_tpl_vars['target'] != ''):  echo ' target="';  echo $this->_tpl_vars['target'];  echo '"';  endif;  echo ' data-role="button" data-icon="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_icon'])) ? $this->_run_mod_handler('default', true, $_tmp, 'arrow-r') : smarty_modifier_default($_tmp, 'arrow-r'));  echo '" data-iconpos="notext" data-theme="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c'));  echo '" data-inline="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true'));  echo '" data-mini="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false'));  echo '"';  if ($this->_tpl_vars['rel_external']):  echo ' rel="external"';  endif;  echo '>';  echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp));  echo '</a>'; ?>

  <?php endif;  elseif ($this->_tpl_vars['is_link']): ?>

  <a class="button<?php if ($this->_tpl_vars['additional_button_class']): ?> <?php echo $this->_tpl_vars['additional_button_class'];  endif; ?>" href="<?php echo $this->_tpl_vars['href']; ?>
" onclick="<?php if ($this->_tpl_vars['js_link']):  echo $this->_tpl_vars['js_link']; ?>
;<?php else: ?>javascript:<?php endif; ?> if (event) event.cancelBubble = true;" title="<?php echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
"<?php if ($this->_tpl_vars['button_id']): ?> id="<?php echo ((is_array($_tmp=$this->_tpl_vars['button_id'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
"<?php endif; ?> data-role="button" data-theme="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c')); ?>
" data-inline="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true')); ?>
"<?php if ($this->_tpl_vars['data_icon']): ?> data-icon="<?php echo $this->_tpl_vars['data_icon']; ?>
" data-iconpos="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_iconpos'])) ? $this->_run_mod_handler('default', true, $_tmp, 'right') : smarty_modifier_default($_tmp, 'right')); ?>
"<?php endif; ?> data-mini="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false')); ?>
"<?php if ($this->_tpl_vars['rel_external']): ?> rel="external"<?php endif; ?>><?php echo ((is_array($_tmp=$this->_tpl_vars['button_title'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp)); ?>
</a>

<?php elseif ($this->_tpl_vars['style'] == 'dropout'): ?>
    <a href="#dropout_btn_<?php echo ((is_array($_tmp=@$this->_tpl_vars['prefix'])) ? $this->_run_mod_handler('default', true, $_tmp, 'dropout') : smarty_modifier_default($_tmp, 'dropout')); ?>
_<?php echo $this->_tpl_vars['dropout_id']; ?>
" data-rel="popup" class="button<?php if ($this->_tpl_vars['additional_button_class']): ?> <?php echo $this->_tpl_vars['additional_button_class'];  endif; ?>" title="<?php echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
" data-role="button" data-theme="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c')); ?>
" data-inline="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true')); ?>
"<?php if ($this->_tpl_vars['data_icon']): ?> data-icon="<?php echo $this->_tpl_vars['data_icon']; ?>
" data-iconpos="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_iconpos'])) ? $this->_run_mod_handler('default', true, $_tmp, 'right') : smarty_modifier_default($_tmp, 'right')); ?>
"<?php endif; ?> data-mini="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false')); ?>
"<?php if ($this->_tpl_vars['rel_external']): ?> rel="external"<?php endif; ?>><?php echo ((is_array($_tmp=$this->_tpl_vars['button_title'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp)); ?>
</a>
  <div id="dropout_btn_<?php echo ((is_array($_tmp=@$this->_tpl_vars['prefix'])) ? $this->_run_mod_handler('default', true, $_tmp, 'dropout') : smarty_modifier_default($_tmp, 'dropout')); ?>
_<?php echo $this->_tpl_vars['dropout_id']; ?>
" data-role="popup" data-theme="<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['data_popup_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['data_theme']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['data_theme'])))) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c')); ?>
">
    <a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-left"><?php echo $this->_tpl_vars['lng']['lbl_close']; ?>
</a>
    <?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => $this->_tpl_vars['dropout_tpl'], 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?>
  </div>

<?php elseif ($this->_tpl_vars['style'] == 'div_button'): ?>
  <div class="button<?php if ($this->_tpl_vars['additional_button_class']): ?> <?php echo $this->_tpl_vars['additional_button_class'];  endif; ?>" title="<?php echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
"<?php if ($this->_tpl_vars['js_link']): ?> onclick="<?php echo $this->_tpl_vars['js_link']; ?>
"<?php endif;  if ($this->_tpl_vars['button_id']): ?> id="<?php echo ((is_array($_tmp=$this->_tpl_vars['button_id'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?>
"<?php endif; ?>  data-role="button"<?php if ($this->_tpl_vars['data_icon']): ?> data-icon="<?php echo $this->_tpl_vars['data_icon']; ?>
" data-iconpos="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_iconpos'])) ? $this->_run_mod_handler('default', true, $_tmp, 'right') : smarty_modifier_default($_tmp, 'right')); ?>
"<?php endif; ?> data-theme="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c')); ?>
" data-inline="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true')); ?>
" data-mini="<?php echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false')); ?>
">
    <?php echo ((is_array($_tmp=$this->_tpl_vars['button_title'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp)); ?>

  </div>
<?php else: ?>
  <?php echo '<button class="button';  if ($this->_tpl_vars['additional_button_class']):  echo ' ';  echo $this->_tpl_vars['additional_button_class'];  echo '';  endif;  echo '" type="';  if ($this->_tpl_vars['type'] == 'input'):  echo 'submit';  else:  echo 'button';  endif;  echo '" title="';  echo ((is_array($_tmp=((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['title'])) ? $this->_run_mod_handler('default', true, $_tmp, @$this->_tpl_vars['button_title']) : smarty_modifier_default($_tmp, @$this->_tpl_vars['button_title'])))) ? $this->_run_mod_handler('strip_tags', true, $_tmp) : smarty_modifier_strip_tags($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp));  echo '"';  if ($this->_tpl_vars['js_link']):  echo ' onclick="';  echo $this->_tpl_vars['js_link'];  echo '"';  endif;  echo '';  if ($this->_tpl_vars['button_id']):  echo ' id="';  echo ((is_array($_tmp=$this->_tpl_vars['button_id'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp));  echo '"';  endif;  echo ' data-theme="';  if ($this->_tpl_vars['type'] == 'input'):  echo '';  echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'b') : smarty_modifier_default($_tmp, 'b'));  echo '';  else:  echo '';  echo ((is_array($_tmp=@$this->_tpl_vars['data_theme'])) ? $this->_run_mod_handler('default', true, $_tmp, 'c') : smarty_modifier_default($_tmp, 'c'));  echo '';  endif;  echo '" data-inline="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_inline'])) ? $this->_run_mod_handler('default', true, $_tmp, 'true') : smarty_modifier_default($_tmp, 'true'));  echo '"';  if ($this->_tpl_vars['data_icon']):  echo ' data-icon="';  echo $this->_tpl_vars['data_icon'];  echo '" data-iconpos="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_iconpos'])) ? $this->_run_mod_handler('default', true, $_tmp, 'right') : smarty_modifier_default($_tmp, 'right'));  echo '"';  endif;  echo ' data-mini="';  echo ((is_array($_tmp=@$this->_tpl_vars['data_mini'])) ? $this->_run_mod_handler('default', true, $_tmp, 'false') : smarty_modifier_default($_tmp, 'false'));  echo '">';  echo ((is_array($_tmp=$this->_tpl_vars['button_title'])) ? $this->_run_mod_handler('amp', true, $_tmp) : smarty_modifier_amp($_tmp));  echo '</button>'; ?>

<?php endif;  if ($this->_tpl_vars['x_core_started']):  echo x_tpl_fire_event(array('name' => 'after','tpl' => "customer/buttons/button.tpl"), $this); endif; ?>