import { StoreDto } from "@s3stores-mail/ts/types";

export const initialValues: StoreDto = {
  items: [],
  itemsCount: undefined,
  searchOptions: {
    from: "",
    to: "",
    subject: "",
    dateAfter: null,
    dateBefore: null,
    hasAttachment: false,
    distributorId: undefined,
  },
  emailInfo: {
    account_id: "",
    action: {
      action: false,
    },
    attachment: [],
    body: "",
    date: new Date(),
    delivered_to_address: "",
    favorite: false,
    from_address: "",
    id: "",
    message_id: "",
    parent_id: null,
    reply_to: null,
    snippet: null,
    subject: "",
    thread_id: "",
    to_address: null,
    type: "",
    viewed: false,
  },
  templateType: {
    name: "Select receiving party",
  },
  sendTemplate: {
    template_name: undefined,
    message_body: "",
  },
  sendData: {
    date: null,
    replyText: "",
    body: "",
    files: [],
    to: [],
    subject: "",
  },
  checkedItems: [],
  checkedItemsOptions: {
    prevValue: "0",
  },
  user: {},
  page: 0,
  loading: false,
  moreViewed: false,
  moreFavorites: false,
  templates: [],
};
