<?php

require "./auth.php";

set_time_limit(0);

if ($mode != "generate_asdlkaysd8927346whrfqw74924kj4hrw9efuwersdrt5wer") die("Mode incorrect!");

define('MANAGE_CATEGORIES', 1);
require $xcart_dir."/include/categories.php";

$resource_types = array("S", "M", "C", "P");

foreach ($resource_types as $k => $resource_type){

	$resource_ids = db_query("SELECT resource_id FROM $sql_tbl[clean_urls] WHERE resource_type='$resource_type'");

	while ($resource_id = db_fetch_array($resource_ids)) {

		if ($resource_type == "S"){

		} elseif ($resource_type == "C"){

		} elseif ($resource_type == "P"){

		} elseif ($resource_type == "M"){

		}

	}
}



$resources_data = func_clean_url_get_resources_data();


$log_filename = "x-errors_clean_url-" . date('ymd') . ".php";
$log_path = $var_dirs['log'] . '/' .$log_filename;
$log_url = "get_log.php?file=" . $log_filename;
$logf = @fopen($log_path, 'w');

$current_date = date(
        "d-M-Y H:i:s",
        time() + $config['Appearance']['timezone_offset']
);

$message =<<<OUT
Date: $current_date
Launched by: $login

OUT;

fwrite($logf, X_LOG_SIGNATURE . $message);


$generated = 0;
$failed = 0;
$last_error_title = false;

foreach ($resource_types as $k => $resource_type){

        if (!in_array($resource_type, array_keys($resources_data))) {
            continue;
        }

        $resource = $resources_data[$resource_type];


        echo "<br />\n"
            . func_get_langvar_by_name(
                'txt_generating_clean_urls_for',
                array(
                    'resource_name' => $resource['resource_name'],
                ),
                false,
                true
            )
            . "<br />\n";

	@header('Content-Encoding: none;');
	func_flush();

        $cnt = 0;

        $fetch_columns         = $resource['params'];
        $fetch_columns[]     = $resource['resource_id_column'];

        $res = db_query("SELECT ".join(",", $fetch_columns)." FROM $resource[resource_table] ".($resource_type == 'S' ? " WHERE level='E'" : ""));

        if (!$res) {
            continue;
        }

        while ($row = db_fetch_array($res)) {

            $params = array();

            foreach ($row as $column => $value) {

                if (in_array($column, $resource['params'])) {

                    $params[$column] = $value;

                }

            }

	    db_query("DELETE FROM $sql_tbl[clean_urls] WHERE resource_type='$resource_type' AND resource_id='".$row[$resource['resource_id_column']]."'");

            $autogenerated_url = func_clean_url_autogenerate($resource_type, $row[$resource['resource_id_column']], $params);

            if ($autogenerated_url == -1) // Clean URL must not be generated for static page (M:0074029)
                continue;

            if (empty($autogenerated_url)) {

                $failed++;
                $cnt++;

                func_clean_url_add_generate_log($logf, $resource_type, $row[$resource['resource_id_column']], $params);

                continue;
            }

            if (!func_clean_url_add($autogenerated_url, $resource_type, $row[$resource['resource_id_column']])) {

                $failed++;
                $cnt++;

                func_clean_url_add_generate_log($logf, $resource_type, $row[$resource['resource_id_column']], $params);

                continue;
            }

            $generated++;
            $cnt++;

            if ($cnt % 10 == 0) {

		@header('Content-Encoding: none;');
                func_flush('.');

                if ($cnt % 500 == 0) {
			@header('Content-Encoding: none;');
			func_flush("<br />\n");
                }

            }


        } // /while

        db_free_result($res);

} // /foreach

//fclose($logf);

print"<br /><br />DONE!";

?>
