version: '3.7'

services:
  # MySQL
  mysql:
    container_name: mysql
    image: percona/percona-server:8.0
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - frontend
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 8Ap6dvSWVJ7r8U8x
      MYSQL_DATABASE: xcart_k
      MYSQL_USER: xcart_k
      MYSQL_PASSWORD: i250923lst
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      TZ: EST
    ports:
      - '3306:3306'
    volumes:
#      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my_dev.cnf:/etc/my.cnf.d/my.cnf
      - ./docker/mysql/slave.cnf:/etc/my.cnf.d/repl.cnf


  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - php
    tty: true
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/configs/:/etc/nginx/configs/
      - ./docker/nginx/sites/:/etc/nginx/sites-enabled.d/
      - ./docker/certbot/conf:/etc/letsencrypt

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    networks:
      - frontend
      - backend
#      - elastic
    depends_on:
      - mysql
      - redis
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: serverName=localhost
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/php/sendmail.ini:/usr/local/etc/php/conf.d/mail.ini
      - ./docker/php/msmtprc:/etc/msmtprc

  redis:
    container_name: redis
    image: redis
    networks:
      - frontend
      - backend
    ports:
      - "6379:6379"
    restart: always
    privileged: true

  node:
    container_name: node
    image: "node:14"
    user: "node"
    working_dir: /home/node/app/www/static
    tty: true
    networks:
      - frontend
    #environment:
    #  - NODE_ENV=production
    volumes:
      - ./:/home/node/app


      #  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
#    container_name: elasticsearch
#    restart: unless-stopped
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=true
#      - xpack.security.authc.api_key.enabled=true
#      - ELASTIC_PASSWORD=admin
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data1:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - elastic
#
#  ent-search:
#    image: docker.elastic.co/enterprise-search/enterprise-search:7.15.1
#    container_name: ent-search
#    restart: unless-stopped
#    depends_on:
#      - elasticsearch
#    environment:
#      - "JAVA_OPTS=-Xms512m -Xmx512m"
#      - ENT_SEARCH_DEFAULT_PASSWORD=adminpass
#      - elasticsearch.username=elastic
#      - elasticsearch.password=admin
#      - elasticsearch.host=http://elasticsearch:9200
#      - allow_es_settings_modification=true
#      - secret_management.encryption_keys=[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]
#      - elasticsearch.startup_retry.interval=15
#    ports:
#      - 3002:3002
#    networks:
#      - elastic
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.15.1
#    container_name: kibana
#    restart: unless-stopped
#    depends_on:
#      - elasticsearch
#      - ent-search
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_HOSTs: http://elasticsearch:9200
#      ENTERPRISESEARCH_HOST: http://ent-search:3002
#      ELASTICSEARCH_USERNAME: elastic
#      ELASTICSEARCH_PASSWORD: admin
#    networks:
#      - elastic

  #nominatim:
  #  container_name: nominatim
  #  image: mediagis/nominatim:3.7
  #  restart: always
  #  ports:
  #    - "8080:8080"
  #  environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/3.7#configuration for more options
  #    PBF_URL: https://download.geofabrik.de/north-america/us-latest.osm.pbf
  #    REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
  #    NOMINATIM_PASSWORD: very_secure_password
  #  volumes:
  #    - nominatim-data:/var/lib/postgresql/12/main
  #  shm_size: 1gb

volumes:
  data1:
    driver: local


networks:
  frontend:
  backend:
#  elastic:
