version: '3.7'

services:
  # MySQL
  mysql:
    container_name: mysql
    image: percona/percona-server:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 8Ap6dvSWVJ7r8U8x
      MYSQL_DATABASE: xcart_k
      MYSQL_USER: xcart_k
      MYSQL_PASSWORD: i250923lst
      TZ: EST
    ports:
      - '3308:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf.d/my.cnf
      #- ./docker/mysql/my_local.cnf:/etc/my.cnf.d/my.cnf

  pmm-server:
    container_name: pmm
    image: percona/pmm-server:latest
    restart: always
    ports:
      - "4443:443"
    environment:
      SERVER_USER: pmm
      SERVER_PASSWORD: pmm
  pmm-client-ps:
    container_name: pmm-client
    image: perconalab/pmm-client:latest
    restart: always
    environment:
      PMM_SERVER: pmm-server:443
      PMM_USER: pmm
      PMM_PASSWORD: pmm
      DB_TYPE: mysql
      DB_HOST: percona-server
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 8Ap6dvSWVJ7r8U8x

  backup:
    container_name: backup
    image: databack/mysql-backup
    restart: always
    volumes:
      - ./docker/mysql/backup/data:/db
      - ./docker/mysql/backup/pre:/scripts.d/pre-backup
      - ./docker/mysql/backup/post:/scripts.d/post-backup
    environment:
      DB_DUMP_TARGET: s3://backup-xcart/dumps
      DB_USER: root
      DB_PASS: 8Ap6dvSWVJ7r8U8x
      DB_DUMP_FREQ: 1440
      DB_DUMP_BEGIN: 0200
      DB_SERVER: mysql
      DB_PORT: 3306
      AWS_ACCESS_KEY_ID: AKIAJPPHD4UZNVAWOBZQ
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-east-1