version: '3.7'

services:
  # MySQL
  mysql:
    container_name: mysql
    image: percona/percona-server:8.0
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - frontend
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 8Ap6dvSWVJ7r8U8x
      MYSQL_DATABASE: xcart_k
      MYSQL_USER: xcart_k
      MYSQL_PASSWORD: i250923lst
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      TZ: EST
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf.d/my.cnf
  smtp:
    restart: always
    container_name: smtp
    image: bambucha/exim-relay
    user: exim
#    ports:
#      - "2525:25"
    volumes:
      - ./docker/smtp/resolv.conf:/etc/resolv.conf
    hostname: mail.s3stores.com
    networks:
      - frontend
      - backend
    environment:
      - RELAY_FROM_HOSTS=10.0.0.0/8:172.16.0.0/12:192.168.0.0/16
      - DKIM_KEY_SIZE=1024
      - DKIM_SELECTOR=dkim
      - DKIM_SIGN_HEADERS=Date:From:To:Subject:Message-ID
      - DKIM_DOMAINS=s3stores.com

#  pmm-server:
#    container_name: pmm
#    image: percona/pmm-server:latest
#    restart: always
#    networks:
#      - backend
#    ports:
#      - "4443:443"
#    environment:
#      SERVER_USER: pmm
#      SERVER_PASSWORD: pmm
#  pmm-client-ps:
#    container_name: pmm-client
#    image: perconalab/pmm-client:latest
#    restart: always
#    networks:
#      - backend
#    environment:
#      PMM_SERVER: pmm-server:443
#      PMM_USER: pmm
#      PMM_PASSWORD: pmm
#      DB_TYPE: mysql
#      DB_HOST: mysql
#      DB_PORT: 3306
#      DB_USER: root
#      DB_PASSWORD: 8Ap6dvSWVJ7r8U8x

  backup:
    container_name: backup
    image: databack/mysql-backup
    restart: always
    networks:
      - backend
    volumes:
      - ./docker/mysql/backup/data:/db
    environment:
      DB_DUMP_TARGET: s3://backup-xcart/dumps
      DB_USER: root
      DB_PASS: 8Ap6dvSWVJ7r8U8x
      DB_DUMP_FREQ: 1440
      DB_DUMP_BEGIN: 0600
      DB_SERVER: mysql
      DB_PORT: 3306
      MYSQLDUMP_OPTS: --single-transaction --routines --triggers --events
      AWS_ACCESS_KEY_ID: AKIAJPPHD4UZNVAWOBZQ
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-east-1

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - php
    tty: true
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - /mnt/disk2/files/images/:/var/www/www/images
      - /mnt/disk2/files/files/:/var/www/www/files
      - /mnt/disk2/files/product_files/:/var/www/www/product_files
      - /mnt/disk2/files/media/:/var/www/www/media
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/configs/:/etc/nginx/configs/
      - ./docker/nginx/sites/:/etc/nginx/sites-enabled.d/
      - ./docker/nginx/logs/:/var/log/nginx/
      - ./docker/certbot/conf:/etc/letsencrypt

  php:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: php
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /mnt/disk2/files/images/:/var/www/www/images
      - /mnt/disk2/files/files/:/var/www/www/files
      - /mnt/disk2/files/product_files/:/var/www/www/product_files
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/prod.ini:/usr/local/etc/php/conf.d/prod.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/sendmail.ini:/usr/local/etc/php/conf.d/mail.ini
      - ./docker/php/msmtprc:/etc/msmtprc


  php-cron:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: php-cron
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      - php
    tty: true
#    command: "/bin/sh -c 'while :; do sleep 1m & wait $${!}; php /var/www/app/console.php Core Cron; done;'"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: serverName=localhost
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - /mnt/disk2/files/images/:/var/www/www/images
      - /mnt/disk2/files/files/:/var/www/www/files
      - /mnt/disk2/files/product_files/:/var/www/www/product_files
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/php/sendmail.ini:/usr/local/etc/php/conf.d/mail.ini
      - ./docker/php/msmtprc:/etc/msmtprc
      - ./docker/php/openssl.cnf:/etc/ssl/openssl.cnf

  redis:
    container_name: redis
    image: redis
    networks:
      - frontend
      - backend
    restart: always

  node:
    container_name: node
    image: "node:14"
    user: "node"
    working_dir: /home/node/app/www/static
    tty: true
    networks:
      - frontend
    #environment:
    #  - NODE_ENV=production
    volumes:
      - ./:/home/node/app

  certbot:
    container_name: certbot
    image: certbot/dns-route53
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - nginx
    tty: true
    entrypoint: "/bin/sh -c 'trap exit TERM;
       openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048;
       certbot certonly -v -n --force-renewal --cert-name s3stores --dns-route53 --agree-tos --email romann@s3stores.com -d s3stores.com,*.7sportinggoods.com,*.acuhealthcare.com,*.artarama.ru,*.artistsupplysource.com,*.astrojewelry.com,*.directship.eu,*.directship.ru,*.electronictoolbox.com,*.furnishingsmart.com,*.justpokersupplies.com,*.kidstuffstation.com,*.kolinskyartbrushes.com,*.lovelyholidaygifts.com,*.musicalinstrumentshoppe.com,*.officesupplysource.com,*.organiclifesource.com,*.petsuppliesplace.com,*.readyfreddie.com,*.ritualsupply.com,*.s3stores.com,*.sincerewedding.com,*.teachersupplysource.com,*.thebulkfoods.com,*.toucheairbrush.com,7sportinggoods.com,acuhealthcare.com,artarama.ru,artistsupplysource.com,astrojewelry.com,directship.eu,directship.ru,electronictoolbox.com,furnishingsmart.com,justpokersupplies.com,kidstuffstation.com,kolinskyartbrushes.com,lovelyholidaygifts.com,musicalinstrumentshoppe.com,officesupplysource.com,organiclifesource.com,petsuppliesplace.com,readyfreddie.com,ritualsupply.com,sincerewedding.com,teachersupplysource.com,thebulkfoods.com,toucheairbrush.com,tacticalsupplysource.com,*.tacticalsupplysource.com,kamasutrasupply.com,*.kamasutrasupply.com,vapecloudshop.com,*.vapecloudshop.com,readyfreddy.ru,*.readyfreddy.ru,gofreddy.ca,*.gofreddy.ca,photovideosupply.com,*.photovideosupply.com,securitygearsupply.com,*.securitygearsupply.com,exhibitionsupply.com,*.exhibitionsupply.com,beautyqueensupply.com,*.beautyqueensupply.com,iconicfashionshop.com,*.iconicfashionshop.com,funeralsupplysource.com,*.funeralsupplysource.com,sweethomesupply.com,*.sweethomesupply.com,autopartsdesk.com,*.autopartsdesk.com,giantindustrialsupply.com,*.giantindustrialsupply.com,healthyfoodsupplements.com,*.healthyfoodsupplements.com,covidremedysupply.com,*.covidremedysupply.com,eddyselectronics.com,*.eddyselectronics.com,donaldsdollarshop.com,*.donaldsdollarshop.com,smarthousesupply.com,*.smarthousesupply.com,wertheimstein.com,*.wertheimstein.com,*.liquidationmonkey.com,liquidationmonkey.com,*.wholesaledonkey.com,wholesaledonkey.com,*.rndlabsupply.com,rndlabsupply.com;
       while :; do certbot renew; sleep 24h & wait $${!}; done;'"
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
    environment:
      AWS_ACCESS_KEY_ID: AKIA5YFRXSHY7JXWQAIR
      AWS_SECRET_ACCESS_KEY: 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

networks:
  frontend:
  backend:
