{*
/**
 * XML template
 *
 * @copyright   Copyright (c) 2001-2010 Creative Development LLC <info@cdev.ru>. All rights reserved
 * @license     http://www.x-cart.com/software_license_agreement.html X-Cart license agreement
 * @author      Slam <slam@x-cart.com>
 * @category    X-Cart
 * @package     Modules
 * @subpackage  XML Sitemap
 * @version     $Id$
 * @since       4.4.0
 */
*}
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.google.com/schemas/sitemap/0.84 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!--#Generated by 'X-SEO: XML Sitemap' generator by Qualiteam software, http://www.qtmsoft.com/, http://www.x-cart.com/ -->
{section name="i" loop=$xmlmap_items}
{strip}
	<url>
		<loc>
			{$xmlmap_items[i].loc}
		</loc>
	{if $xmlmap_items[i].lastmod ne ""}	
		<lastmod>
			{$xmlmap_items[i].lastmod}
		</lastmod>
	{/if}
		<changefreq>
			{$xmlmap_items[i].changefreq}
		</changefreq>
		<priority>
			{$xmlmap_items[i].priority}
		</priority>
	</url>
{/strip}
{/section}
</urlset>
