; Skin name
name="Icons menu"

; Flag indicating that the skin uses layers.
layer="Y"

; Flag indicating that the skin uses dynamic loading of subcategory blocks.
download="Y"

; Skin attribute indicating what function must be called from the onload event in the <BODY> tag.
onload="fcOnLoad();"

; Below follow descriptions of the skin variables.
;
; Each variable must be placed into a separate section; the name of the section must be the name of the variable (for example, [variable_1]).
;
; Inside each section the following attributes must be described:
;   type: can take the following values: numeric, text, checkbox, selector, multiselector, textarea
;   default: variable value by default
;   description: variable description
;
; A variable may also have the following optional fields:
;   critical: takes the value of "Y" if the value of this variable affects the appearance of the category block.
; If you want to create descriptions of the variable in more than one language, you can create additional fields for these descriptions.
; The names of such fields must have the format 'description_XX', where XX is the code of the language (for example, description_DE for a 
; description in the German language).
;
; If the 'type' attribute of a variable is specified as 'selector' or 'multiselector', it is necessary to describe the variants of values
; the variable may take. This can be done using an array of variable attributes with names variant0...variantn. For example:
; variant0="1:red"
; variant1="2:green"
; variant2="3:blue"
; variant3="4:white"
;
; This set will be converted into the following <OPTION>...</OPTION> tag set:
; <OPTION value="1">red</OPTION>
; <OPTION value="2">green</OPTION>
; <OPTION value="3">blue</OPTION>
; <OPTION value="4">white</OPTION>
;
; Mind that variant fields may be numbered randomly. For example:
; variant100="1:red"
; variant11="2:green"
; variant2="3:blue"
; variant43="4:white"
;
; or
;
; variant0="1:red"
; variant11="2:green"
; variant22="3:blue"
; variant33="4:white"
;
; The numeration will not affect the way in which the select-box with the set of variants of variable values will be displayed.

[icons_in_categories]
type=selector
default=1
description="Display icons for categories"
description_US="Display icons for categories"
description_DE="Icons für Kategorien anzeigen"
description_FR="Montrer les icônes pour les catégories"
critical=Y
variant0="0:none"
variant1="1:only root (level1)"
variant2="2:up to level2"
variant3="3:up to level3"
variant4="4:up to level4"
variant5="5:up to level5"
variant6="6:up to level6"
variant7="7:up to level7"
variant8="8:up to level8"
variant9="9:up to level9"
variant10="10:up to level10"

[disable_subcat_triangle]
type=checkbox
default=N
description="Don't display subcategories triangle"
description_US="Don't display subcategories triangle"
description_DE="Unterkategorien-Dreieck neben den Kategoriennamen nicht anzeigen"
description_FR="Ne pas montrer le triangle de souscatégories"
critical=Y
