{*
/**
 * XML template
 *
 * @copyright   Copyright (c) 2001-2010 Creative Development LLC <info@cdev.ru>. All rights reserved
 * @license     http://www.x-cart.com/software_license_agreement.html X-Cart license agreement
 * @author      Slam <slam@x-cart.com>
 * @category    X-Cart
 * @package     Modules
 * @subpackage  XML Sitemap
 * @version     $Id$
 * @since       4.4.0
 */
*}
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<!--#Generated by 'X-SEO: XML Sitemap' generator by Qualiteam software, http://www.qtmsoft.com/, http://www.x-cart.com/ -->
{section name="i" loop=$xmlindex_items}
{strip}
        <sitemap>
                <loc>{$xmlindex_items[i].loc}</loc>
{*
        {if $xmlindex_items[i].lastmod ne ""}
                <lastmod>{$xmlindex_items[i].lastmod}</lastmod>
        {/if}
*}
		<lastmod>{$cur_date}</lastmod>
        </sitemap>
{/strip}
{/section}
</sitemapindex>
