<?php
return [
    'Core',
    'Admin',
    'Editor',
    'Files',
    'Cart' => ['cartConfig' => ['class' => '\Modules\Cart\Components\XCart']],
    'Meta',
    'Menu',
    'Mail',
    'Dashboard',
    'Distributor',
    'Product',
    'Order',
    'Shipping',
    'User'   => ['sessionTime' => 15552000],
    'Sites'  => ['defaultStore' => 'AR'],
    'Amazon',
    'Order',
    'Reports',
    'Brand',
    'Pages',
    'Amp',
];