<?php
return [
    'Core',
    'Admin',
    'Editor',
    'Files',
    'Cart' => ['cartConfig' => ['class' => '\Modules\Cart\Components\XCart']],
    'Main',
    'Meta',
    'Menu',
    'Slider',
    'Mail',
    'Demo',
    'Dashboard',
    'Distributor',
    'Goods',
    'Order',
    'Shipping',
    'User'   => ['EXP_TIME_S' => 180 * 24 * 60 * 60],
    'Sites'  => ['defaultStore' => 'AR'],
    'Amazon',
    'Order',
    'Reports',
    'Brand',
    'Forms',
    'Pages',
    'Amp',
    'PBX',
    'Shipping',
    'Landing',
    'Subscribe',
    'Xero',
    'Translate',
    'Help',
    'Account',
    'Reviews',
    'Images',
    'Media',
];