<?php

namespace Xcart\App\Form\Fields;


class PercentField extends NumberField
{
    public function getAttributes()
    {
        return parent::getAttributes(); // TODO: Change the autogenerated stub
    }
}
