server {

    listen 80;
    server_name s3stores.com localhost
    index index index.php controllers.php controller.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/www;

    include configs/content_cache.conf;

    location ~ ^/(provider|admin)/$ {
        include configs/stores_admin_auth.conf;
    }

    location ~ ^/(modules|var|includes).* {
        return 301 /;
    }

    location ~ /include/.*/.* {
        return 301 /;
    }

    location ~ \.php$ {
        fastcgi_cache xcart_cache;
        fastcgi_cache_valid 200 60m;
        fastcgi_cache_bypass $no_cache;
        fastcgi_no_cache $no_cache;
        fastcgi_ignore_headers Cache-Control Expires Set-Cookie;
        add_header X-Proxy-Cache    $upstream_cache_status;

        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php74-fpm-backend;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param QUERY_STRING $query_string;
    }

    location ~* ^.+\.(css|js)$ {
        expires 31536000;
    }
    location ~* ^.+\.(jpg|jpeg|gif|png|svg|bpm)$ {
        expires 31536000;
        add_header Cache-Control "public";

        log_not_found off;
        access_log off;
    }

    location ~* ^.+\.(ttf|woff|woff2|eot)$ {
        add_header Access-Control-Allow-Origin *;
        expires 31536000;
    }

    location /admin/ {
        try_files $uri $uri/ /admin/index.php?$args;
        gzip_static on;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
        gzip_static on;
    }

    # Rewrite rules (sitemaps)
    rewrite ^/robots.txt /robots.txt.php last;
    rewrite ^/sitemap.xml /sitemap.xml.php last;

    client_max_body_size 0;

}