<?php

namespace Modules\Goods\Models;


use Xcart\App\Orm\Model;

class FeaturedProductsModel extends Model
{
    public static function tableName()
    {
        return  'xcart_featured_products';
    }

    public static function getFields()
    {
        return parent::getFields(); // TODO: Change the autogenerated stub
    }

}