<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
    'MarketplaceWebService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MarketplaceWebServiceSellers_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MarketplaceWebServiceProducts_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MarketplaceWebServiceOrders_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MWSSubscriptionsService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MWSRecommendationsSectionService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MWSMerchantFulfillmentService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MWSFinancesService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MWSCustomerService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'MWSCartService_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Google_Service_' => array($vendorDir . '/google/apiclient-services/src'),
    'Google_' => array($vendorDir . '/google/apiclient/src'),
    'Fenom\\' => array($vendorDir . '/fenom/fenom/src'),
    'FBAOutboundServiceMWS_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'FBAInventoryServiceMWS_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'FBAInboundServiceMWS_' => array($vendorDir . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'CaponicaAmazonMwsComplete\\' => array($vendorDir . '/caponica/amazon-mws-complete/src'),
);
