<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92
{
    public static $files = array (
        '2c102faa651ef8ea5874edb585946bce' => __DIR__ . '/..' . '/swiftmailer/swiftmailer/lib/swift_required.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        'e40631d46120a9c38ea139981f8dab26' => __DIR__ . '/..' . '/ircmaxell/password-compat/lib/password.php',
        '3e2471375464aac821502deb0ac64275' => __DIR__ . '/..' . '/symfony/polyfill-php54/bootstrap.php',
        'edc6464955a37aa4d5fbf39d40fb6ee7' => __DIR__ . '/..' . '/symfony/polyfill-php55/bootstrap.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'bd9634f2d41831496de0d3dfe4c94881' => __DIR__ . '/..' . '/symfony/polyfill-php56/bootstrap.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
        '68f9084e889ebf718663435970ab45e3' => __DIR__ . '/..' . '/mindy/query_builder/src/Conditions.php',
        'f29a2007f2178ee4ae11496b92ada6d1' => __DIR__ . '/../../../..' . '/app/include/func/func.core.php',
        '3d0a72febcb8a483969ed811c9d351f7' => __DIR__ . '/../../../..' . '/app/include/func/func.amazon.php',
        '8a5fbc4004d1d6ab9474ee26d4d26a67' => __DIR__ . '/../../../..' . '/app/include/func/func.backoffice.php',
        '41152f076ea83bb54a480e7000e49960' => __DIR__ . '/../../../..' . '/app/include/func/func.cart.php',
        '085bd63b35db17112eb31e921f7ccf43' => __DIR__ . '/../../../..' . '/app/include/func/func.category.php',
        '9cf3537736a9bdbbcb8d164d812c6828' => __DIR__ . '/../../../..' . '/app/include/func/func.clean_urls.php',
        '29adaf4312708b38e29c8b6371959dc9' => __DIR__ . '/../../../..' . '/app/include/func/func.crypt.php',
        '85abc9befa3f49590258c273e8d3307d' => __DIR__ . '/../../../..' . '/app/include/func/func.db.php',
        '63d27390f537864f2ad8f18be77454d9' => __DIR__ . '/../../../..' . '/app/include/func/func.export.php',
        '902d0319291f4eb276aaabcf6a089b18' => __DIR__ . '/../../../..' . '/app/include/func/func.files.php',
        'cd66e644d9e955ef61164c53a7efeaa8' => __DIR__ . '/../../../..' . '/app/include/func/func.fraud.php',
        '88a744cb312552c9b44e8d9b96530e76' => __DIR__ . '/../../../..' . '/app/include/func/func.froogle.php',
        'a9a6a07c51db46c5b6589091e7c455e1' => __DIR__ . '/../../../..' . '/app/include/func/func.gd.php',
        '0e2c9dfa1ca2a4b0f0b4f7d5dfcc7339' => __DIR__ . '/../../../..' . '/app/include/func/func.http.php',
        '5231668e240abd5af9f30564cba4777d' => __DIR__ . '/../../../..' . '/app/include/func/func.https_curl.php',
        'a7b2a9bb05ac491e63fcb95816882c36' => __DIR__ . '/../../../..' . '/app/include/func/func.https_httpscli.php',
        'ae282cab3155b4c7fcc6237339132f93' => __DIR__ . '/../../../..' . '/app/include/func/func.https_libcurl.php',
        '82e70948556093aa57b59d3e9c70e1c7' => __DIR__ . '/../../../..' . '/app/include/func/func.https_openssl.php',
        '2107aaa88424e93a732750767ae14d6a' => __DIR__ . '/../../../..' . '/app/include/func/func.https_ssleay.php',
        'a2ed827bf3a609ea9724a33923f5e989' => __DIR__ . '/../../../..' . '/app/include/func/func.image.php',
        'f7b147bc0151029f4742a82b09cc0154' => __DIR__ . '/../../../..' . '/app/include/func/func.import.php',
        'cad4ee127a2bc56a8ba3ebdc29f2d68d' => __DIR__ . '/../../../..' . '/app/include/func/func.mail.php',
        '0474cd79750dc4ed87578bcc0da80b96' => __DIR__ . '/../../../..' . '/app/include/func/func.order.php',
        '2bc33fa736b0ef746a0eb39df8ea059b' => __DIR__ . '/../../../..' . '/app/include/func/func.order_edit.php',
        '7856b0fa80c561f6f6b914b531c14988' => __DIR__ . '/../../../..' . '/app/include/func/func.payment.php',
        '95b8889facdba0255c88b996b08e0295' => __DIR__ . '/../../../..' . '/app/include/func/func.product.php',
        '6cde2fd622429af654e5ad4e0ebf5bff' => __DIR__ . '/../../../..' . '/app/include/func/func.snapshots.php',
        'f083e5ac2c83fe0779aaddc69ef6ea16' => __DIR__ . '/../../../..' . '/app/include/func/func.taxes.php',
        'ea9ce7590dfe484f303defebff06008f' => __DIR__ . '/../../../..' . '/app/include/func/func.templater.php',
        '439368cf5ba298ee1596643cef52adae' => __DIR__ . '/../../../..' . '/app/include/func/func.tests.php',
        'a995d74c3d0337cd2d6f734851668029' => __DIR__ . '/../../../..' . '/app/include/func/func.user.php',
        '466984b3dc8bf99b478ff217bd1893bd' => __DIR__ . '/../../../..' . '/app/include/func/func.xml.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'X' => 
        array (
            'Xcart\\External_Product_Verification\\' => 36,
            'Xcart\\External_Marketplaces\\' => 28,
            'Xcart\\' => 6,
        ),
        'U' => 
        array (
            'Ups\\' => 4,
        ),
        'T' => 
        array (
            'TrueBV\\' => 7,
            'TheIconic\\Tracking\\GoogleAnalytics\\' => 35,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Util\\' => 22,
            'Symfony\\Polyfill\\Php56\\' => 23,
            'Symfony\\Polyfill\\Php55\\' => 23,
            'Symfony\\Polyfill\\Php54\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Validator\\' => 28,
            'Symfony\\Component\\Translation\\' => 30,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\Finder\\' => 25,
            'Symfony\\Component\\EventDispatcher\\' => 34,
            'SuperClosure\\' => 13,
        ),
        'R' => 
        array (
            'React\\Promise\\' => 14,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Cache\\' => 10,
            'PhpParser\\' => 10,
        ),
        'O' => 
        array (
            'Omnipay\\PayPal\\' => 15,
            'Omnipay\\BluePay\\' => 16,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
            'Modules\\' => 8,
            'Mindy\\QueryBuilder\\' => 19,
            'MaxMind\\WebService\\' => 19,
            'MaxMind\\Exception\\' => 18,
            'MaxMind\\Db\\' => 11,
        ),
        'L' => 
        array (
            'League\\Flysystem\\' => 17,
        ),
        'J' => 
        array (
            'Jobby\\' => 6,
            'Jaybizzle\\CrawlerDetect\\' => 24,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Ring\\' => 16,
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\' => 11,
            'Google\\Auth\\' => 12,
            'GeoIp2\\' => 7,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'E' => 
        array (
            'Egulias\\EmailValidator\\' => 23,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Cache\\' => 22,
            'Dariuszp\\' => 9,
        ),
        'C' => 
        array (
            'Cron\\' => 5,
            'Composer\\CaBundle\\' => 18,
            'Cocur\\Slugify\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'Xcart\\External_Product_Verification\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/www/modules/External_Product_Verification/include',
        ),
        'Xcart\\External_Marketplaces\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/www/modules/External_Marketplaces/include',
        ),
        'Xcart\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/app/include/Xcart',
        ),
        'Ups\\' => 
        array (
            0 => __DIR__ . '/..' . '/gabrielbull/ups-api/src/Ups',
        ),
        'TrueBV\\' => 
        array (
            0 => __DIR__ . '/..' . '/true/punycode/src',
        ),
        'TheIconic\\Tracking\\GoogleAnalytics\\' => 
        array (
            0 => __DIR__ . '/..' . '/theiconic/php-ga-measurement-protocol/src',
        ),
        'Symfony\\Polyfill\\Util\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-util',
        ),
        'Symfony\\Polyfill\\Php56\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php56',
        ),
        'Symfony\\Polyfill\\Php55\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php55',
        ),
        'Symfony\\Polyfill\\Php54\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php54',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Validator\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/validator',
        ),
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'SuperClosure\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeremeamia/SuperClosure/src',
        ),
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
        'Omnipay\\PayPal\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/app/Modules/Payment/Gateways/Omnipay/PayPal',
            1 => __DIR__ . '/..' . '/omnipay/paypal/src',
        ),
        'Omnipay\\BluePay\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/app/Modules/Payment/Gateways/Omnipay/BluePay',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Modules\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/app/Modules',
        ),
        'Mindy\\QueryBuilder\\' => 
        array (
            0 => __DIR__ . '/..' . '/mindy/query_builder/src',
        ),
        'MaxMind\\WebService\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src/WebService',
        ),
        'MaxMind\\Exception\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src/Exception',
        ),
        'MaxMind\\Db\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind-db/reader/src/MaxMind/Db',
        ),
        'League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
        'Jobby\\' => 
        array (
            0 => __DIR__ . '/..' . '/hellogerard/jobby/src',
        ),
        'Jaybizzle\\CrawlerDetect\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaybizzle/crawler-detect/src',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Ring\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/ringphp/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/auth/src',
        ),
        'GeoIp2\\' => 
        array (
            0 => __DIR__ . '/..' . '/geoip2/geoip2/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'Egulias\\EmailValidator\\' => 
        array (
            0 => __DIR__ . '/..' . '/egulias/email-validator/EmailValidator',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'Dariuszp\\' => 
        array (
            0 => __DIR__ . '/..' . '/dariuszp/cli-progress-bar/src/Dariuszp',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowling/cron-expression/src/Cron',
        ),
        'Composer\\CaBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/ca-bundle/src',
        ),
        'Cocur\\Slugify\\' => 
        array (
            0 => __DIR__ . '/..' . '/cocur/slugify/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
        'O' => 
        array (
            'Omnipay\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/omnipay/common/src',
            ),
        ),
        'I' => 
        array (
            'Imagine' => 
            array (
                0 => __DIR__ . '/..' . '/imagine/imagine/lib',
            ),
        ),
        'G' => 
        array (
            'Guzzle\\Tests' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/tests',
            ),
            'Guzzle' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/src',
            ),
            'Google_Service_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient-services/src',
            ),
            'Google_' => 
            array (
                0 => __DIR__ . '/..' . '/google/apiclient/src',
            ),
        ),
        'F' => 
        array (
            'Fenom\\' => 
            array (
                0 => __DIR__ . '/..' . '/fenom/fenom/src',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Inflector\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/inflector/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
            'Doctrine\\Common\\Annotations\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/annotations/lib',
            ),
            'Doctrine\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/common/lib',
            ),
            'Detection' => 
            array (
                0 => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/namespaced',
            ),
        ),
        'C' => 
        array (
            'CaponicaAmazonMwsComplete\\' => 
            array (
                0 => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src',
            ),
        ),
        'A' => 
        array (
            'Aws' => 
            array (
                0 => __DIR__ . '/..' . '/aws/aws-sdk-php/src',
            ),
        ),
    );

    public static $classMap = array (
        'CallbackFilterIterator' => __DIR__ . '/..' . '/symfony/polyfill-php54/Resources/stubs/CallbackFilterIterator.php',
        'Config_File' => __DIR__ . '/../../../..' . '/app/include/smarty/Config_File.class.php',
        'FBAInventoryServiceMWS_Client' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Client.php',
        'FBAInventoryServiceMWS_Exception' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Exception.php',
        'FBAInventoryServiceMWS_Interface' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Interface.php',
        'FBAInventoryServiceMWS_Mock' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Mock.php',
        'FBAInventoryServiceMWS_Model' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAInventoryServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/GetServiceStatusResult.php',
        'FBAInventoryServiceMWS_Model_InventorySupply' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupply.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyDetail' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupplyDetail.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyDetailList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupplyDetailList.php',
        'FBAInventoryServiceMWS_Model_InventorySupplyList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/InventorySupplyList.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenRequest.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenResponse.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyByNextTokenResult.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyRequest.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyResponse.php',
        'FBAInventoryServiceMWS_Model_ListInventorySupplyResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ListInventorySupplyResult.php',
        'FBAInventoryServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAInventoryServiceMWS_Model_ResponseMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/ResponseMetadata.php',
        'FBAInventoryServiceMWS_Model_SellerSkuList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/SellerSkuList.php',
        'FBAInventoryServiceMWS_Model_Timepoint' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAInventoryServiceMWS/Model/Timepoint.php',
        'FBAOutboundServiceMWS_Client' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Client.php',
        'FBAOutboundServiceMWS_Exception' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Exception.php',
        'FBAOutboundServiceMWS_Interface' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Interface.php',
        'FBAOutboundServiceMWS_Mock' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Mock.php',
        'FBAOutboundServiceMWS_Model' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model.php',
        'FBAOutboundServiceMWS_Model_Address' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Address.php',
        'FBAOutboundServiceMWS_Model_CODSettings' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CODSettings.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CancelFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CancelFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentReturnRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentReturnRequest.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentReturnResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentReturnResponse.php',
        'FBAOutboundServiceMWS_Model_CreateFulfillmentReturnResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateFulfillmentReturnResult.php',
        'FBAOutboundServiceMWS_Model_CreateReturnItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateReturnItem.php',
        'FBAOutboundServiceMWS_Model_CreateReturnItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/CreateReturnItemList.php',
        'FBAOutboundServiceMWS_Model_Currency' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Currency.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindow' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/DeliveryWindow.php',
        'FBAOutboundServiceMWS_Model_DeliveryWindowList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/DeliveryWindowList.php',
        'FBAOutboundServiceMWS_Model_Fee' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Fee.php',
        'FBAOutboundServiceMWS_Model_FeeList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FeeList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentMethodList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentMethodList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrder' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrder.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentOrderList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentOrderList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreview' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreview.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipment' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentPreviewShipmentList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentPreviewShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipment' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipment.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentItem.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentItemList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentList.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackage' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackage.php',
        'FBAOutboundServiceMWS_Model_FulfillmentShipmentPackageList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/FulfillmentShipmentPackageList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentOrderResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentOrderResult.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItem.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewItemList.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewRequest.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResponse.php',
        'FBAOutboundServiceMWS_Model_GetFulfillmentPreviewResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetFulfillmentPreviewResult.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsRequest.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResponse.php',
        'FBAOutboundServiceMWS_Model_GetPackageTrackingDetailsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetPackageTrackingDetailsResult.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetServiceStatusRequest.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetServiceStatusResponse.php',
        'FBAOutboundServiceMWS_Model_GetServiceStatusResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/GetServiceStatusResult.php',
        'FBAOutboundServiceMWS_Model_InvalidItemReason' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/InvalidItemReason.php',
        'FBAOutboundServiceMWS_Model_InvalidReturnItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/InvalidReturnItem.php',
        'FBAOutboundServiceMWS_Model_InvalidReturnItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/InvalidReturnItemList.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersByNextTokenResult.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersRequest.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResponse.php',
        'FBAOutboundServiceMWS_Model_ListAllFulfillmentOrdersResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListAllFulfillmentOrdersResult.php',
        'FBAOutboundServiceMWS_Model_ListReturnReasonCodesRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListReturnReasonCodesRequest.php',
        'FBAOutboundServiceMWS_Model_ListReturnReasonCodesResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListReturnReasonCodesResponse.php',
        'FBAOutboundServiceMWS_Model_ListReturnReasonCodesResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ListReturnReasonCodesResult.php',
        'FBAOutboundServiceMWS_Model_NotificationEmailList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/NotificationEmailList.php',
        'FBAOutboundServiceMWS_Model_ReasonCodeDetails' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReasonCodeDetails.php',
        'FBAOutboundServiceMWS_Model_ReasonCodeDetailsList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReasonCodeDetailsList.php',
        'FBAOutboundServiceMWS_Model_ResponseHeaderMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ResponseHeaderMetadata.php',
        'FBAOutboundServiceMWS_Model_ResponseMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ResponseMetadata.php',
        'FBAOutboundServiceMWS_Model_ReturnAuthorization' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnAuthorization.php',
        'FBAOutboundServiceMWS_Model_ReturnAuthorizationList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnAuthorizationList.php',
        'FBAOutboundServiceMWS_Model_ReturnItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnItem.php',
        'FBAOutboundServiceMWS_Model_ReturnItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ReturnItemList.php',
        'FBAOutboundServiceMWS_Model_ScheduledDeliveryInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ScheduledDeliveryInfo.php',
        'FBAOutboundServiceMWS_Model_ShippingSpeedCategoryList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/ShippingSpeedCategoryList.php',
        'FBAOutboundServiceMWS_Model_StringList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/StringList.php',
        'FBAOutboundServiceMWS_Model_TrackingAddress' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/TrackingAddress.php',
        'FBAOutboundServiceMWS_Model_TrackingEvent' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/TrackingEvent.php',
        'FBAOutboundServiceMWS_Model_TrackingEventList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/TrackingEventList.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItem.php',
        'FBAOutboundServiceMWS_Model_UnfulfillablePreviewItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UnfulfillablePreviewItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItem' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItem.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderItemList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderItemList.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderRequest.php',
        'FBAOutboundServiceMWS_Model_UpdateFulfillmentOrderResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/UpdateFulfillmentOrderResponse.php',
        'FBAOutboundServiceMWS_Model_Weight' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/FBAOutboundServiceMWS/Model/Weight.php',
        'Fenom' => __DIR__ . '/..' . '/fenom/fenom/src/Fenom.php',
        'Google_Service_Exception' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Exception.php',
        'Google_Service_Resource' => __DIR__ . '/..' . '/google/apiclient/src/Google/Service/Resource.php',
        'MarketplaceWebService_Client' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Client.php',
        'MarketplaceWebService_Exception' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Exception.php',
        'MarketplaceWebService_Interface' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Interface.php',
        'MarketplaceWebService_Mock' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Mock.php',
        'MarketplaceWebService_Model' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelFeedSubmissionsRequest.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelFeedSubmissionsResponse.php',
        'MarketplaceWebService_Model_CancelFeedSubmissionsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelFeedSubmissionsResult.php',
        'MarketplaceWebService_Model_CancelReportRequestsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelReportRequestsRequest.php',
        'MarketplaceWebService_Model_CancelReportRequestsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelReportRequestsResponse.php',
        'MarketplaceWebService_Model_CancelReportRequestsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/CancelReportRequestsResult.php',
        'MarketplaceWebService_Model_ContentType' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ContentType.php',
        'MarketplaceWebService_Model_Error' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/Error.php',
        'MarketplaceWebService_Model_ErrorResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ErrorResponse.php',
        'MarketplaceWebService_Model_FeedSubmissionInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/FeedSubmissionInfo.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionCountRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionCountResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionCountResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionListResult.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionResultRequest.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionResultResponse.php',
        'MarketplaceWebService_Model_GetFeedSubmissionResultResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetFeedSubmissionResultResult.php',
        'MarketplaceWebService_Model_GetReportCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportCountRequest.php',
        'MarketplaceWebService_Model_GetReportCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportCountResponse.php',
        'MarketplaceWebService_Model_GetReportCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportCountResult.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListRequest.php',
        'MarketplaceWebService_Model_GetReportListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListResponse.php',
        'MarketplaceWebService_Model_GetReportListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportListResult.php',
        'MarketplaceWebService_Model_GetReportRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestCountRequest.php',
        'MarketplaceWebService_Model_GetReportRequestCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestCountResponse.php',
        'MarketplaceWebService_Model_GetReportRequestCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestCountResult.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportRequestListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListRequest.php',
        'MarketplaceWebService_Model_GetReportRequestListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListResponse.php',
        'MarketplaceWebService_Model_GetReportRequestListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportRequestListResult.php',
        'MarketplaceWebService_Model_GetReportResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportResponse.php',
        'MarketplaceWebService_Model_GetReportResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportResult.php',
        'MarketplaceWebService_Model_GetReportScheduleCountRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleCountRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleCountResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleCountResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleCountResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListByNextTokenRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListByNextTokenResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListByNextTokenResult.php',
        'MarketplaceWebService_Model_GetReportScheduleListRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListRequest.php',
        'MarketplaceWebService_Model_GetReportScheduleListResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListResponse.php',
        'MarketplaceWebService_Model_GetReportScheduleListResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/GetReportScheduleListResult.php',
        'MarketplaceWebService_Model_IdList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/IdList.php',
        'MarketplaceWebService_Model_ManageReportScheduleRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ManageReportScheduleRequest.php',
        'MarketplaceWebService_Model_ManageReportScheduleResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ManageReportScheduleResponse.php',
        'MarketplaceWebService_Model_ManageReportScheduleResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ManageReportScheduleResult.php',
        'MarketplaceWebService_Model_ReportInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ReportInfo.php',
        'MarketplaceWebService_Model_ReportRequestInfo' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ReportRequestInfo.php',
        'MarketplaceWebService_Model_ReportSchedule' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ReportSchedule.php',
        'MarketplaceWebService_Model_RequestReportRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/RequestReportRequest.php',
        'MarketplaceWebService_Model_RequestReportResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/RequestReportResponse.php',
        'MarketplaceWebService_Model_RequestReportResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/RequestReportResult.php',
        'MarketplaceWebService_Model_ResponseHeaderMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ResponseHeaderMetadata.php',
        'MarketplaceWebService_Model_ResponseMetadata' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/ResponseMetadata.php',
        'MarketplaceWebService_Model_StatusList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/StatusList.php',
        'MarketplaceWebService_Model_SubmitFeedRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/SubmitFeedRequest.php',
        'MarketplaceWebService_Model_SubmitFeedResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/SubmitFeedResponse.php',
        'MarketplaceWebService_Model_SubmitFeedResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/SubmitFeedResult.php',
        'MarketplaceWebService_Model_TypeList' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/TypeList.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsRequest' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/UpdateReportAcknowledgementsRequest.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResponse' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/UpdateReportAcknowledgementsResponse.php',
        'MarketplaceWebService_Model_UpdateReportAcknowledgementsResult' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/Model/UpdateReportAcknowledgementsResult.php',
        'Mobile_Detect' => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/Mobile_Detect.php',
        'Omnipay\\Omnipay' => __DIR__ . '/..' . '/omnipay/common/src/Omnipay/Omnipay.php',
        'RecursiveCallbackFilterIterator' => __DIR__ . '/..' . '/symfony/polyfill-php54/Resources/stubs/RecursiveCallbackFilterIterator.php',
        'RequestType' => __DIR__ . '/..' . '/caponica/amazon-mws-complete/src/AmazonPhpClientLibrary/MarketplaceWebService/RequestType.php',
        'SessionHandlerInterface' => __DIR__ . '/..' . '/symfony/polyfill-php54/Resources/stubs/SessionHandlerInterface.php',
        'Smarty' => __DIR__ . '/../../../..' . '/app/include/smarty/Smarty.class.php',
        'Smarty_Compiler' => __DIR__ . '/../../../..' . '/app/include/smarty/Smarty_Compiler.class.php',
        'TemplateCompiler' => __DIR__ . '/../../../..' . '/app/include/templater/templater.php',
        'Templater' => __DIR__ . '/../../../..' . '/app/include/templater/templater.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$prefixesPsr0;
            $loader->classMap = ComposerStaticInited1e2f7cb4425e4bdc0264910bb94e92::$classMap;

        }, null, ClassLoader::class);
    }
}
