; Skin name
name="Candy menu"

; Flag indicating that the skin uses layers.
layer="Y"

; Flag indicating that the skin uses dynamic loading of subcategory blocks.
download="Y"

; Skin attribute indicating what function must be called from the onload event in the <BODY> tag.
onload="fcOnLoad();"

; Below follow descriptions of the skin variables.
;
; Each variable must be placed into a separate section; the name of the section must be the name of the variable (for example, [variable_1]).
;
; Inside each section the following attributes must be described:
;   type: can take the following values: numeric, text, checkbox, selector, multiselector, textarea
;   default: variable value by default
;   description: variable description
;
; A variable may also have the following optional fields:
;   critical: takes the value of "Y" if the value of this variable affects the appearance of the category block.
; If you want to create descriptions of the variable in more than one language, you can create additional fields for these descriptions.
; The names of such fields must have the format 'description_XX', where XX is the code of the language (for example, description_DE for a 
; description in the German language).
;
; If the 'type' attribute of a variable is specified as 'selector' or 'multiselector', it is necessary to describe the variants of values
; the variable may take. This can be done using an array of variable attributes with names variant0...variantn. For example:
; variant0="1:red"
; variant1="2:green"
; variant2="3:blue"
; variant3="4:white"
;
; This set will be converted into the following <OPTION>...</OPTION> tag set:
; <OPTION value="1">red</OPTION>
; <OPTION value="2">green</OPTION>
; <OPTION value="3">blue</OPTION>
; <OPTION value="4">white</OPTION>
;
; Mind that variant fields may be numbered randomly. For example:
; variant100="1:red"
; variant11="2:green"
; variant2="3:blue"
; variant43="4:white"
;
; or
;
; variant0="1:red"
; variant11="2:green"
; variant22="3:blue"
; variant33="4:white"
;
; The numeration will not affect the way in which the select-box with the set of variants of variable values will be displayed.

[img_skin]
type=selector
default=candy1
description="Select an image set for the current style"
description_US="Select an image set for the current style"
description_DE="Bildsatz für den aktuellen Stil wählen"
description_FR="Sélectionner une ensemble d'images pour le style courant"
critical=Y
variant0="candy1:Brown"
variant1="candy2:Blue"
variant2="candy3:Green"
variant3="candy4:Violet"

[truncate]
type=numeric
default=20
description="Number of characters in a category name to which the category name length will be truncated"
description_US="Number of characters in a category name to which the category name length will be truncated"
description_DE="Maximale Anzahl von Zeichen in einem Kategoriennamen; längere Kategoriennamen werden auf diese Länge gekürzt"
critical=Y
