<?php
namespace Modules\Dashboard\Models;

use Xcart\App\Main\Xcart;
use Xcart\App\Orm\Fields\AutoField;
use Xcart\App\Orm\Fields\BooleanField;
use Xcart\App\Orm\Fields\IntField;
use Xcart\App\Orm\Fields\JsonField;
use Xcart\App\Orm\Fields\TextField;
use Xcart\App\Orm\Model;

class DashboardFilter extends Model
{
    public static function tableName()
    {
//        return "{{dashboard_filters}}";
        return "xcart_dashboard_filters";
    }

    public static function getFields()
    {
        return [
            'id' => [
                'class' => AutoField::className(),
            ],
            'enabled' => [
                'class' => BooleanField::className(),
                'null' => false,
                'default' => 0,
            ],
            'bold' => [
                'class' => BooleanField::className(),
                'null' => false,
                'default' => 0
            ],
            'name' => [
                'class' => TextField::className(),
                'null' => false,
                'verboseName' => 'Filter name'
            ],
            'position_row' => [
                'class' => IntField::className(),
                'null' => false,
            ],
            'position_column' => [
                'class' => IntField::className(),
                'null' => false
            ],
            'tag' => [
                'class' => TextField::className(),
                'length' => 5,
                'null' => false
            ],
            'color' => [
                'class' => TextField::className(),
                'null' => false,
                'verboseName' => 'Tag color'
            ],
            'form_data' => [
                'class' => JsonField::className(),
                'null' => false,
                'verboseName' => 'Filter condition'
            ]
        ];
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getAdminUrl()
    {
        if ($this->isNewRecord) {
            return Xcart::app()->router->url('dashboard:create');
        }
        else {
            return Xcart::app()->router->url('dashboard:edit', ['id' => $this->id]);
        }
    }

    public function afterSave($owner, $isNew)
    {
        parent::afterSave($owner, $isNew); // TODO: Change the autogenerated stub
    }
}