<?php
namespace Modules\Dashboard\Models;

use Xcart\App\Main\Xcart;
use Xcart\App\Orm\Fields\AutoField;
use Xcart\App\Orm\Fields\CharField;
use Xcart\App\Orm\Fields\HasManyField;
use Xcart\App\Orm\Model;

class GroupModel extends Model
{
    public static function tableName()
    {
        return 'xcart_dashboard_groups';
    }

    public static function getFields()
    {
        return [
            'id' => [
                'class' => AutoField::classname()
            ],
            'name' => [
                'class' => CharField::className(),
                'null' => false,
                'verboseName' => 'Group name'
            ],
            'filters' => [
                'class' => HasManyField::className(),
                'modelClass' => DashboardFilter::className(),
                'verboseName' => 'Filters',
                'link' => ['id' => 'group_id'],
            ]
        ];
    }

    public function afterDelete($owner)
    {
        parent::afterDelete($owner);
        DashboardFilter::objects()->filter(['group_id' => $owner->id])->update(['group_id' => null]);
    }

    public function getAdminUrl()
    {
        if ($this->isNewRecord) {
            return Xcart::app()->router->url('dashboard:create_group');
        }
        else {
            return Xcart::app()->router->url('dashboard:update_group', ['id' => $this->id]);
        }
    }

    public function __toString()
    {
        return $this->name; // TODO: Change the autogenerated stub
    }
}