server {
    listen 80;
    server_name www.businesssupplysource.com;

    return 301 https://www.officesupplysource.com$request_uri;
}

server {
    listen 443 ssl http2;

    server_name www.businesssupplysource.com;

    return 301 https://www.officesupplysource.com$request_uri;
}