server {
    listen 80;
    server_name www.huntersupplysource.com;

    return 301 https://www.tacticalsupplysource.com$request_uri;
}

server {
    listen 443 ssl http2;

    server_name www.huntersupplysource.com;

    return 301 https://www.tacticalsupplysource.com$request_uri;
}