server {
    listen 80;
    server_name www.kolinskyartbrushes.com;

    return 301 https://www.artistsupplysource.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.kolinskyartbrushes.com;

    return 301 https://www.artistsupplysource.com$request_uri;
}