server {
    listen 443;
    server_name secure.s3stores.com alpha18.artistsupplysource.com;

    access_log /var/www/xpay/log/nginx-access.log combined;
    error_log /var/www/xpay/log/nginx-error.log error;

    include /srv/nginx/configs/stores_ssl.conf;


    root "/var/www/xpay/www";
    location / {
        index index.php index.html;
    }

    include /srv/nginx/configs/location_deny.conf;
    include /srv/nginx/configs/error_pages.conf;
    include /srv/nginx/configs/cache_static.conf;

    # PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php71-fpm-backend;
        fastcgi_param   SCRIPT_FILENAME     $document_root/$fastcgi_script_name;
        fastcgi_param   QUERY_STRING        $query_string;
    }
}

# HTTP Redirect
server {
    listen 80;
    server_name secure.s3stores.com alpha18.artistsupplysource.com;
    return 302 https://$host$request_uri;
}
