
server {
    listen 80;
    server_name old.artistsupplysource.com old.test.artistsupplysource.com;

    root /var/www/old/xcart/www;

    location / {
        return 301 https://$host$request_uri;
    }

    location = /loginpbx.php {
        include /srv/nginx/configs/stores_index_files.conf;
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_param   SCRIPT_FILENAME     $document_root/loginpbx.php;
        fastcgi_param   QUERY_STRING        $query_string;
    }

    location ~ ^/pbx/call/(.*)$ {
        include /srv/nginx/configs/stores_index_files.conf;
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_param   SCRIPT_FILENAME     $document_root/index.php;
        fastcgi_param   QUERY_STRING        $query_string;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name old.artistsupplysource.com old.test.artistsupplysource.com;

    root /var/www/old/xcart/www;

    access_log /var/www/old/xcart/log/nginx-access.log combined;
    error_log /var/www/old/xcart/log/nginx-error.log error;

    include /srv/nginx/configs/limit_connections.conf;
    include /srv/nginx/configs/compress.conf;

    include /srv/nginx/configs/stores_ssl.conf;
    include /srv/nginx/configs/stores_base.conf;
    #include /srv/nginx/configs/stores_new_design.conf;
}