
server {
    listen 80 reuseport default_server;

    root /var/www/www;

    location / {
        return 301 https://$host$request_uri;
    }

    location = /loginpbx.php {
        include /srv/nginx/configs/stores_index_files.conf;
        include fastcgi_params;
        fastcgi_pass php74-fpm-backend;
        fastcgi_param   SCRIPT_FILENAME     $document_root/loginpbx.php;
        fastcgi_param   QUERY_STRING        $query_string;
    }

    location ~ ^/pbx/call/(.*)$ {
        include /srv/nginx/configs/stores_index_files.conf;
        include fastcgi_params;
        fastcgi_pass php74-fpm-backend;
        fastcgi_param   SCRIPT_FILENAME     $document_root/index.php;
        fastcgi_param   QUERY_STRING        $query_string;
    }
}

# HTTPS
server {
    listen 443 ssl http2 reuseport default_server;

    root /var/www/production/www;

    access_log /var/www/production/log/nginx-access.log combined;
    error_log /var/www/production/log/nginx-error.log error;

    include /srv/nginx/configs/limit_connections.conf;
    include /srv/nginx/configs/compress.conf;

    include /srv/nginx/configs/stores_ssl.conf;
    #include /srv/nginx/configs/stores_base.conf;
    include /srv/nginx/configs/stores_new_design.conf;
}