; Skin name
name="Explorer"

; Below follow descriptions of the skin variables.
;
; Each variable must be placed into a separate section; the name of the section must be the name of the variable (for example, [variable_1]).
;
; Inside each section the following attributes must be described:
;   type: can take the following values: numeric, text, checkbox, selector, multiselector, textarea
;   default: variable value by default
;   description: variable description
;
; A variable may also have the following optional fields:
;   critical: takes the value of "Y" if the value of this variable affects the appearance of the category block.
; If you want to create descriptions of the variable in more than one language, you can create additional fields for these descriptions.
; The names of such fields must have the format 'description_XX', where XX is the code of the language (for example, description_DE for a 
; description in the German language).
;
; If the 'type' attribute of a variable is specified as 'selector' or 'multiselector', it is necessary to describe the variants of values
; the variable may take. This can be done using an array of variable attributes with names variant0...variantn. For example:
; variant0="1:red"
; variant1="2:green"
; variant2="3:blue"
; variant3="4:white"
;
; This set will be converted into the following <OPTION>...</OPTION> tag set:
; <OPTION value="1">red</OPTION>
; <OPTION value="2">green</OPTION>
; <OPTION value="3">blue</OPTION>
; <OPTION value="4">white</OPTION>
;
; Mind that variant fields may be numbered randomly. For example:
; variant100="1:red"
; variant11="2:green"
; variant2="3:blue"
; variant43="4:white"
;
; or
;
; variant0="1:red"
; variant11="2:green"
; variant22="3:blue"
; variant33="4:white"
;
; The numeration will not affect the way in which the select-box with the set of variants of variable values will be displayed.

[img_skin]
type=selector
default=std
description="Select an image set for the current style"
description_US="Select an image set for the current style"
description_DE="Bildsatz für den aktuellen Stil wählen"
description_FR="Sélectionner l'ensemble d'images pour le style courant"
variant0="std:Classic"
variant1="blue:Icy Blue"
variant2="xp:XP Style"

[diff_categories]
type=checkbox
default=Y
description="Use a different icon for categories containing products not organized into subcategories"
description_US="Use a different icon for categories containing products not organized into subcategories"
description_DE="Ein verschiedenes Bild für die Kategorien verwenden, die keine Unterkategorien besitzen"
description_FR="User une icône différente pour les catégories contenantes les produits qui ne sont pas arrangés dans les souscatégories"

[nowrap_categories]
type=checkbox
default=N
description="Prevent categories names wrapping"
description_US="Prevent categories names wrapping"
description_DE="Zeilenumbruch in Kategoriennamen verhindern"
description_FR="Prévenir le raccourcissement de noms de catégories"

[count_products]
type=checkbox
default=Y
description="Show number of products in subcategories"
description_US="Show number of products in subcategories"
description_DE="Die Anzahl der Artikel und Unterkategorien als Tooltip anzeigen"
