6801dcf0db04076b2a95207d480e1b94a:20:{s:18:"lbl_applying_patch";s:14:"Applying patch";s:15:"lbl_apply_patch";s:11:"Apply patch";s:29:"lbl_files_excluded_from_patch";s:35:"Files excluded from patch procedure";s:22:"lbl_files_patch_status";s:18:"Files patch status";s:10:"lbl_finish";s:6:"Finish";s:11:"lbl_go_back";s:7:"Go Back";s:13:"lbl_patch_log";s:9:"PATCH LOG";s:17:"lbl_patch_results";s:13:"PATCH RESULTS";s:14:"lbl_patch_text";s:10:"Patch text";s:28:"lbl_tick_here_to_apply_patch";s:62:"Tick here if you want to try to apply the patch to these files";s:25:"txt_applying_patch_step_1";s:69:"Step 1 of 2: Testing patch applicability and generation list of files";s:25:"txt_applying_patch_step_2";s:31:"Step 2 of 2: Applying the patch";s:18:"txt_correct_errors";s:56:"Please correct the errors displayed above and try again.";s:30:"txt_files_could_not_be_patched";s:232:"<b>Warning!</b><br />
The following files could not be patched with automated upgrade system. This may be because these files were changed from their original state. Those files needs to be patched manually or restored from backup.";s:24:"txt_have_could_not_patch";s:116:"<b>Warning</b>:<br />
Some of files in your installation got the status "<font color="red">could not patch</font>".";s:27:"txt_patch_application_error";s:338:"<font color="red"><b>Error!</b></font><br />
One of files in your installation got one of the following status:
<font color="red">checksum error</font>,
<font color="red">non-writable</font>,
<font color="red">not a file</font>.<br />
This is critical error. Patch/upgrade process cannot continue.<br />
Please correct these errors.";s:29:"txt_patch_applied_successfuly";s:30:"Patch was applied successfully";s:23:"txt_patch_applying_note";s:90:"<b>Note:</b>
After applying a patch please set the original permissions on changed files.";s:30:"txt_some_files_will_be_ignored";s:137:"<b>Note:</b><br />
Files which <font color="red">do not exist</font> and <font color="blue">were already patched</font> will be ignored.";s:24:"txt_testing_phase_result";s:30:"Result of the testing phase...";}