07122f157fa88a8194240a5d8a7116e1a:24:{s:18:"err_billing_county";s:89:"Incorrect county for billing address (the county does not belong to the specified state).";s:17:"err_billing_state";s:89:"Incorrect state for billing address (the state does not belong to the specified country).";s:19:"err_shipping_county";s:90:"Incorrect county for shipping address (the county does not belong to the specified state).";s:18:"err_shipping_state";s:90:"Incorrect state for shipping address (the state does not belong to the specified country).";s:20:"err_username_invalid";s:121:"You have specified an incorrect username. Only numbers (0-9) and lower-case letters (a-z) can be used. Please correct it.";s:27:"lbl_create_customer_profile";s:23:"Create customer profile";s:18:"lbl_create_profile";s:14:"Create Profile";s:27:"lbl_modify_customer_profile";s:23:"Modify customer profile";s:18:"lbl_modify_profile";s:14:"Modify profile";s:28:"lbl_return_to_search_results";s:28:"Return to the search results";s:8:"lbl_save";s:4:"Save";s:27:"txt_create_customer_profile";s:52:"This section allows you to create customer profiles.";s:24:"txt_email_already_exists";s:42:"Email address already exists in database !";s:17:"txt_email_invalid";s:41:"E-mail address is invalid! Please correct";s:27:"txt_modify_customer_profile";s:51:"This section allows you to modify customer profile.";s:22:"txt_modify_profile_msg";s:0:"";s:30:"txt_newbie_registration_bottom";s:148:"<b>Privacy Policy</b>
<hr noshade="noshade" size="1">
All your private data is confidential. We will never sell, exchange or market it in any way.";s:19:"txt_partner_created";s:56:"Thank you, you are registered as a partner of the store.";s:19:"txt_profile_created";s:362:"Thank you, your user profile has been successfully created.<br />
<br />
A confirmation e-mail has been sent to the email address that you entered. You can use these details to log in to our website in future. This will make your purchase even easier.<br />
<br />
Now that your account is active and you are logged in you may continue with your purchases.
";s:20:"txt_profile_modified";s:31:"Your profile has been modified.";s:22:"txt_registration_error";s:142:"The form is filled in with errors !<br />Check that you have entered all mandatory values.<br />Check that your password matches confirmation.";s:36:"txt_terms_and_conditions_newbie_note";s:0:"";s:23:"txt_user_already_exists";s:20:"User already exists!";s:28:"txt_user_registration_bottom";s:277:"<b>Information
</b>
<br /><br />
The password must be different from the username. It is strongly recommended to use passwords of 5 or more characters.
<br /><br />
E-mail address must be valid because it will be used for communication purposes (order notifications, etc).";}