<?php
define("CIDEV_CRON_START", "CRON");

require "./top.inc.php";
require "./init.php";

ini_set('memory_limit', '512M');
set_time_limit(0);

define('MANAGE_CATEGORIES', 1);
require $xcart_dir."/include/categories.php";

$resource_types = array("S", "M", "C", "P");

foreach ($resource_types as $k => $resource_type){

	$resource_ids = db_query("SELECT SQL_NO_CACHE resource_id FROM $sql_tbl[clean_urls] WHERE resource_type='$resource_type'");

	while ($resource_id = db_fetch_array($resource_ids)) {

		if ($resource_type == "S"){

		} elseif ($resource_type == "C"){

		} elseif ($resource_type == "P"){

		} elseif ($resource_type == "M"){

		}

	}
}

$resources_data = func_clean_url_get_resources_data();

$generated = 0;
$failed = 0;
$last_error_title = false;

foreach ($resource_types as $k => $resource_type){

        if (!in_array($resource_type, array_keys($resources_data))) {
            continue;
        }

        $resource = $resources_data[$resource_type];


        echo "<br />\n"
            . func_get_langvar_by_name(
                'txt_generating_clean_urls_for',
                array(
                    'resource_name' => $resource['resource_name'],
                ),
                false,
                true
            )
            . "<br />\n";

	func_flush();

        $cnt = 0;

        $fetch_columns         = $resource['params'];
        $fetch_columns[]     = $resource['resource_id_column'];

        $res = db_query("SELECT SQL_NO_CACHE ".join(",", $fetch_columns)." FROM $resource[resource_table] ".($resource_type == 'S' ? " WHERE level='E'" : ""));

        if (!$res) {
            continue;
        }

        while ($row = db_fetch_array($res)) {

            $params = array();

            foreach ($row as $column => $value) {

                if (in_array($column, $resource['params'])) {

                    $params[$column] = $value;

                }

            }

	    db_query("DELETE FROM $sql_tbl[clean_urls] WHERE resource_type='$resource_type' AND resource_id='".$row[$resource['resource_id_column']]."'");

            $autogenerated_url = func_clean_url_autogenerate($resource_type, $row[$resource['resource_id_column']], $params);

            if ($autogenerated_url == -1) // Clean URL must not be generated for static page (M:0074029)
                continue;

            if (empty($autogenerated_url)) {
                $failed++;
                $cnt++;
                continue;
            }

            if (!func_clean_url_add($autogenerated_url, $resource_type, $row[$resource['resource_id_column']])) {

                $failed++;
                $cnt++;

                continue;
            }

            $generated++;
            $cnt++;

            if ($cnt % 10 == 0) {
                func_flush('.');
                if ($cnt % 500 == 0) {
			func_flush("<br />\n");
                }
            }
        } // /while

        db_free_result($res);
} // /foreach

//fclose($logf);

print"<br />DONE!";

?>
