#-----------------------------------------------#
# Начало блока конфигурации хоста
#-----------------------------------------------#

server {
    listen         %ip%:%httpport%;
    listen         %ip%:%httpsport% ssl;
    server_name    %host% %aliases%;
	root                          '%hostdir%';
    
    ssl_certificate               "%sprogdir%/userdata/config/cert_files/server.crt";
    ssl_certificate_key           "%sprogdir%/userdata/config/cert_files/server.key";
    
   # Force HTTPS
	add_header Strict-Transport-Security 'max-age=2592000' always;
	if ($scheme ~* ^(?!https).*$) {
		return 301 https://$host$request_uri;
	}
	location ~* ^.+\.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv|svgz?|ttf|ttc|otf|eot|woff2?)$ {
        expires 1d;
        access_log off;
	}
    




location = /analytics.js {
proxy_pass https://www.google-analytics.com;
expires 7d;
}
location = /plugins/ua/linkid.js {
proxy_pass https://www.google-analytics.com;
expires 7d;
}
location = /plugins/ua/ec.js {
proxy_pass https://www.google-analytics.com;
expires 7d;
}

location /images {
try_files $uri /default_image.gif;
}


location ~ ^/(provider|admin)/(.*)$ {
    rewrite ^/.+$ /admin/controllers.php last;
}


location / {
    # Force index.php routing (if not found)
    # try_files $uri $uri/ /index.php?$query_string;


    # Force index.php routing (all requests)
     rewrite ^/(.*)$ /index.php?/$1 last;

    location ~ \.php$ {
        try_files      $fastcgi_script_name =404;

        # limit_conn   addr 16;
        # limit_req    zone=flood        burst=32 nodelay;

        # add_header   X-Frame-Options   'SAMEORIGIN' always;
        # add_header   Referrer-Policy   'no-referrer-when-downgrade' always;

        # CSP syntax: <host-source> <scheme-source>(http: https: data: mediastream: blob: filesystem:) 'self' 'unsafe-inline' 'unsafe-eval' 'none'
        # Content-Security-Policy-Report-Only (report-uri https://site.com/csp/)
        # add_header   Content-Security-Policy  "default-src 'self'; connect-src 'self'; font-src 'self'; frame-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; object-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'; upgrade-insecure-requests" always;

        fastcgi_pass   backend;
        include        '%sprogdir%/userdata/config/nginx_fastcgi_params.txt';
    }
}
}