<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 27.12.2016
 * Time: 13:47
 */

namespace Xcart\Helpers\CrawlerDetect;

use Jaybizzle\CrawlerDetect\Fixtures\AbstractProvider;

class Crawlers extends AbstractProvider
{
    protected $data = null;
    private $raw_data
        = ["X-Cart info"                     => ["X-Cart info", 'curl', 'PycURL',"curl/7.21.0", "PycURL/7.19.5"],
           "Other"                           => ["NerdyBot", "ShortLinkTranslate", "YahooCacheSystem", "ContextAd", "WillyBot/1.1", "WorldBrewBot/2.1", "robots",
               "WebIndex", "Wget/", "Twitterbot/1.0", "YisouSpider", "betaBot", "psbot", "Xenu", "SEOstats", "Wotbox/2.01", "CCBot/2.0", "Spider/Bot", "PHP/5.4.32",
               "tbot", "ltx71", "TurnitinBot", "Disqus/1.0",
           ],
           "FaceBook"                        => ["facebookexternalhit/1.1"],
           "Pinterest"                       => ["Pinterest", "Pinterest/0.2", "Pinterest/0.1", "Pinterest/4.1.1"],
           "Ahrefs"                          => ["AhrefsBot/5.0", "adidxbot/1.1"],
           "Spotbot"                         => ["spotbot - spotbot@indix.com", "DotBot/1.1", "Mail.RU_Bot/2.0", "rogerbot/1.1", "spotbot"],
           "Google"                          => ["Googlebot", "Mediapartners-Google", "AdsBot-Google-Mobile", "AdsBot-Google", "TwengaBot-2.0", "Googlebot-Image/1.0", "GoogleBot/2.1", "TwengaBot", "AdsBot"],
           "Bing"                            => ["bing"],
           "TheFind"                         => ["FatBot", "ShopWiki/1.0", "com.thefind.Shopping/3.2.1"],
           "Excita"                          => ["ArchitextSpider"],
           "Altavista"                       => ["Scooter", "vscooter", "Mercator", "AltaVista-Intranet"],
           "Lycos"                           => ["Lycos_Spider"],
           "Northern Light"                  => ["Gulliver"],
           "AllTheWeb"                       => ["FAST-WebCrawler", "fastlwspider", "Wget"],
           "Inktomi"                         => ["Slurp", "Yahoo!"],
           "Teoma"                           => ["teoma_agent1"],
           "Yandex"                          => ["Yandex", "YandexImages/3.0", "YandexBot/3.0", "YandexBot"],
           "Amazon"                          => ["aranhabot", "Amazon CloudFront", "Amazon"],
           "Yahoo"                           => ["YahooSeeker"],
           "Abacho"                          => ["AbachoBOT"],
           "Abcdatos"                        => ["abcdatos_botlink"],
           "Aesop"                           => ["AESOP_com_SpiderMan"],
           "Ah-ha"                           => ["ah-ha.com crawler"],
           "Alexa"                           => ["ia_archiver"],
           "Acoon"                           => ["Acoon Robot"],
           "Antisearch"                      => ["antibot"],
           "Atomz"                           => ["Atomz"],
           "Buscaplus"                       => ["Buscaplus Robi"],
           "ShopperTom"                      => ["ShopperTom", "MJ12Bot", "Pimonster", "ShopperTom/"],
           "Baidu"                           => ["Baiduspider", "Baiduspider-image", "Sogou", "Baiduspider-image+", "Baiduspider/2.0", "Baiduspider-image+(+http://www.baidu.com/search/spider.htm)"],
           "CanSeek"                         => ["CanSeek"],
           "ChristCrawler"                   => ["ChristCRAWLER"],
           "Crawler"                         => ["Crawler"],
           "Daadle"                          => ["DaAdLe.com ROBOT"],
           "Daum"                            => ["RaBot"],
           "DeepIndex"                       => ["DeepIndex"],
           "Ditto"                           => ["DittoSpyder"],
           "Domanova"                        => ["Jack"],
           "Entire web"                      => ["Speedy Spider"],
           "Euroseek"                        => ["Arachnoidea"],
           "EZResults"                       => ["EZResult"],
           "Fast search"                     => ["Fast PartnerSite Crawler", "FAST Data Search Crawler"],
           "Fireball"                        => ["KIT-Fireball"],
           "Fyber search"                    => ["FyberSearch"],
           "Galaxy"                          => ["GalaxyBot"],
           "Geckobot"                        => ["geckobot"],
           "GenDoor"                         => ["GenCrawler"],
           "Geona"                           => ["GeonaBot"],
           "Goo"                             => ["moget/2.0"],
           "Girafa"                          => ["Aranha"],
           "Hoppa"                           => ["Toutatis"],
           "Hubat"                           => ["Hubater"],
           "IlTrovatore"                     => ["IlTrovatore-Setaccio"],
           "IncyWincy"                       => ["IncyWincy"],
           "InTags"                          => ["Mole2"],
           "MP3Bot"                          => ["MP3Bot"],
           "IP3000"                          => ["ip3000.com-crawler"],
           "Kuloko"                          => ["kuloko-bot"],
           "Lexis-Nexis"                     => ["LNSpiderguy"],
           "Look"                            => ["NetResearchServer"],
           "Look smart"                      => ["MantraAgent"],
           "Loop improvements"               => ["NetResearchServer"],
           "Joocer"                          => ["JoocerBot"],
           "Mirage"                          => ["HenryTheMiragoRobot"],
           "mozDex"                          => ["mozDex"],
           "MSN"                             => ["MSNBOT", "msnbot-media", "msnbot"],
           "Northern light"                  => ["Gulliver"],
           "Objects Search"                  => ["ObjectsSearch"],
           "Pico Search"                     => ["PicoSearch"],
           "Portal Juice"                    => ["PJspider"],
           "Maxbot"                          => ["Spider/maxbot.com"],
           "National directory"              => ["NationalDirectory-SuperSpider"],
           "Naver"                           => ["NaverRobot"],
           "OpenFind"                        => ["Openfind piranha", "Openbot"],
           "Pic search"                      => ["psbot"],
           "PinPoint"                        => ["CrawlerBoy Pinpoint.com"],
           "Search hippo"                    => ["Fluffy the spider"],
           "Scrub the Web"                   => ["Scrubby"],
           "SingingFish"                     => ["asterias"],
           "SpeedFind"                       => ["speedfind ramBot xtreme"],
           "Kototoi"                         => ["Kototoi"],
           "SearchSpider"                    => ["Searchspider"],
           "SightQuest"                      => ["SightQuestBot"],
           "SpiderMonkey"                    => ["Spider_Monkey"],
           "Surf-no-more"                    => ["Surfnomore Spider"],
           "Teradex Mapper"                  => ["Teradex_Mapper"],
           "Travel finder"                   => ["ESISmartSpider"],
           "TraficDublu"                     => ["Spider TraficDublu"],
           "Tutorgig"                        => ["Tutorial Crawler"],
           "UK Searcher"                     => ["UK Searcher Spider"],
           "Vivante"                         => ["Vivante Link Checker"],
           "Walhello"                        => ["appie"],
           "Websmostlinked.com"              => ["Nazilla"],
           "WebTop"                          => ["MuscatFerret"],
           "WiseNut"                         => ["ZyBorg"],
           "World search center"             => ["WSCbot"],
           "Yellow pet"                      => ["Yellopet-Spider"],
           "W3C validator"                   => ["W3C_Validator"],
           "Tooter"                          => ["Tooter"],
           "Alligator"                       => ["Alligator"],
           "BatchFTP"                        => ["BatchFTP"],
           "ChinaClaw"                       => ["ChinaClaw"],
           "Download accelerator"            => ["DA"],
           "NetZIP"                          => ["Download Demon", "NetZip Downloader", "SmartDownload"],
           "Download Master"                 => ["Download Master"],
           "Download Ninja"                  => ["Download Ninja"],
           "Download Wonder"                 => ["Download Wonder"],
           "Ez Auto Downloader"              => ["Ez Auto Downloader"],
           "FreshDownload"                   => ["FreshDownload"],
           "Go!Zilla"                        => ["Go!Zilla"],
           "GetRight"                        => ["GetRight"],
           "GetSmart"                        => ["GetSmart"],
           "HiDownload"                      => ["HiDownload"],
           "FlagGet"                         => ["JetCar", "FlashGet"],
           "Kapere"                          => ["Kapere"],
           "Kontiki"                         => ["Kontiki Client"],
           "LeechFTP"                        => ["LeechFTP"],
           "LeechGet"                        => ["LeechGet"],
           "LightningDownload"               => ["LightningDownload"],
           "Mass Downloader"                 => ["Mass Downloader"],
           "MetaProducts"                    => ["MetaProducts"],
           "NetAnts"                         => ["NetAnts"],
           "NetButler"                       => ["NetButler"],
           "NetPumper"                       => ["NetPumper"],
           "Net Vampire"                     => ["Net Vampire"],
           "Nitro Downloader"                => ["Nitro Downloader"],
           "Octopus"                         => ["Octopus"],
           "PuxaRapido"                      => ["PuxaRapido"],
           "RealDownload"                    => ["RealDownload"],
           "SpeedDownload"                   => ["SpeedDownload"],
           "WebDownloader"                   => ["WebDownloader"],
           "WebLeacher"                      => ["WebLeacher"],
           "WebPictures"                     => ["WebPictures"],
           "X-Uploader"                      => ["X-Uploader"],
           "DigOut4U"                        => ["DigOut4U"],
           "DISCoFinder"                     => ["DISCoFinder"],
           "eCatch"                          => ["eCatch"],
           "EirGrabber"                      => ["EirGrabber"],
           "ExtractorPro"                    => ["ExtractorPro"],
           "FairAd"                          => ["FairAd Client"],
           "iSiloWeb"                        => ["iSiloWeb"],
           "Kenjin"                          => ["Kenjin Spider"],
           "MS IE 4.0"                       => ["MSIECrawler", "MSProxy"],
           "NexTools"                        => ["NexTools"],
           "Offline Explorer"                => ["Offline Explorer"],
           "NetAttache"                      => ["NetAttache"],
           "PageDown"                        => ["PageDown"],
           "ParaSite"                        => ["ParaSite"],
           "Searchworks"                     => ["Searchworks Spider"],
           "SiteMapper"                      => ["SiteMapper"],
           "SiteSnagger"                     => ["SiteSnagger"],
           "SuperBot"                        => ["SuperBot"],
           "Teleport Pro"                    => ["Teleport Pro"],
           "Web2Map"                         => ["Web2Map"],
           "WebAuto"                         => ["WebAuto"],
           "WebCopier"                       => ["WebCopier"],
           "Webdup"                          => ["Webdup"],
           "WebFetch"                        => ["WebFetch"],
           "WebReaper"                       => ["WebReaper"],
           "Webrobot"                        => ["Webrobot"],
           "Website eXtractor"               => ["Website eXtractor"],
           "WebSnatcher"                     => ["WebSnatcher"],
           "WebStripper"                     => ["WebStripper"],
           "WebTwin"                         => ["WebTwin"],
           "WebVCR"                          => ["WebVCR"],
           "WebZIP"                          => ["WebZIP"],
           "World Wide Web Offline Explorer" => ["WWWOFFLE"],
           "Xaldon"                          => ["Xaldon WebSpider"],
           "spbot"                           => ["spbot"],
           "Qwantify"                        => ["Qwantify"],
           "BLEXBot"                         => ["BLEXBot"],
           "IstellaBot"                      => ["istellabot/"],
        ];

    private function clearData($data)
    {
        return preg_replace('/([\+\/\\\.@\(\)])/i', '\\\${1}', $data);
    }

    public function __construct()
    {
        $data = [];
        foreach ($this->raw_data as $k => $v) {
            $v      = $this->clearData(implode('|', $v));
            $data[] = "($v)";
        }
        $this->data = $data;
    }

    public function getCrawlerName($n)
    {
        $h = array_keys($this->raw_data);

        return $h[$n];
    }

}