<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 27.12.2016
 * Time: 13:47
 */

namespace Xcart\Helpers\CrawlerDetect;

use Jaybizzle\CrawlerDetect\Fixtures\AbstractProvider;

class Crawlers extends AbstractProvider
{
    protected $data
        = [
            "X-Cart info",
            "curl",
            "PycURL",
            "ShortLinkTranslate",
            "YahooCacheSystem",
            "ContextAd",
            "WillyBot",
            "WorldBrewBot",
            "robots",
            "WebIndex",
            "Wget",
            "Twitterbot",
            "YisouSpider",
            "betaBot",
            "psbot",
            "Xenu",
            "SEOstats",
            "Wotbox",
            "CCBot",
            "Spider/Bot",
            "PHP/5.4.32",
            "tbot",
            "ltx71",
            "TurnitinBot",
            "Disqus",
            "facebookexternalhit",
            "Pinterest",
            "Pinterest/0.2",
            "Pinterest/0.1",
            "Pinterest/4.1.1",
            "AhrefsBot/5.0",
            "adidxbot/1.1",
            "spotbot - spotbot@indix.com",
            "DotBot/1.1",
            "Mail.RU_Bot/2.0",
            "rogerbot/1.1",
            "spotbot",
            "Googlebot",
            "Mediapartners-Google",
            "AdsBot-Google-Mobile",
            "AdsBot-Google",
            "TwengaBot-2.0",
            "Googlebot-Image/1.0",
            "GoogleBot/2.1",
            "TwengaBot",
            "AdsBot",
            "bing",
            "FatBot", "ShopWiki/1.0",
            "com.thefind.Shopping/3.2.1",
            "ArchitextSpider",
            "Scooter", "vscooter", "Mercator", "AltaVista-Intranet",
            "Lycos_Spider",
            "Gulliver",
            "FAST-WebCrawler", "fastlwspider", "Wget",
            "Slurp", "Yahoo!",
            "teoma_agent1",
            "Yandex",
            "YandexImages/3.0",
            "YandexBot/3.0", "YandexBot",
            "aranhabot",
            "Amazon CloudFront",
            "Amazon",
            "YahooSeeker",
            "AbachoBOT",
            "abcdatos_botlink",
            "AESOP_com_SpiderMan",
            "ah-ha.com crawler",
            "ia_archiver",
            "Acoon Robot",
            "antibot",
            "Atomz",
            "Buscaplus Robi",
            "ShopperTom",
            "MJ12Bot",
            "Pimonster",
            "ShopperTom/",
            "Baiduspider",
            "Baiduspider-image",
            "Sogou",
            "Baiduspider-image+",
            "Baiduspider/2.0",
            "Baiduspider-image+(+http://www.baidu.com/search/spider.htm)",
            "CanSeek",
            "ChristCRAWLER",
            "Crawler",
            "DaAdLe.com ROBOT",
            "RaBot",
            "DeepIndex",
            "DittoSpyder",
            "Jack",
            "Speedy Spider",
            "Arachnoidea",
            "EZResult",
            "Fast PartnerSite Crawler", "FAST Data Search Crawler",
            "KIT-Fireball",
            "FyberSearch",
            "GalaxyBot",
            "geckobot",
            "GenCrawler",
            "GeonaBot",
            "moget/2.0",
            "Aranha",
            "Toutatis",
            "Hubater",
            "IlTrovatore-Setaccio",
            "IncyWincy",
            "Mole2",
            "MP3Bot",
            "ip3000.com-crawler",
            "kuloko-bot",
            "LNSpiderguy",
            "NetResearchServer",
            "MantraAgent",
            "NetResearchServer",
            "JoocerBot",
            "HenryTheMiragoRobot",
            "mozDex",
            "MSNBOT",
            "msnbot-media",
            "msnbot",
            "Gulliver",
            "ObjectsSearch",
            "PicoSearch",
            "PJspider",
            "Spider/maxbot.com",
            "NationalDirectory-SuperSpider",
            "NaverRobot",
            "Openfind piranha", "Openbot",
            "psbot",
            "CrawlerBoy Pinpoint.com",
            "Fluffy the spider",
            "Scrubby",
            "asterias",
            "speedfind ramBot xtreme",
            "Kototoi",
            "Searchspider",
            "SightQuestBot",
            "Spider_Monkey",
            "Surfnomore Spider",
            "Teradex_Mapper",
            "ESISmartSpider",
            "Spider TraficDublu",
            "Tutorial Crawler",
            "UK Searcher Spider",
            "Vivante Link Checker",
            "appie",
            "Nazilla",
            "MuscatFerret",
            "ZyBorg",
            "WSCbot",
            "Yellopet-Spider",
            "W3C_Validator",
            "Tooter",
            "Alligator",
            "BatchFTP",
            "ChinaClaw",
            "DA",
            "Download Demon", "NetZip Downloader", "SmartDownload",
            "Download Master",
            "Download Ninja",
            "Download Wonder",
            "Ez Auto Downloader",
            "FreshDownload",
            "Go!Zilla",
            "GetRight",
            "GetSmart",
            "HiDownload",
            "JetCar", "FlashGet",
            "Kapere",
            "Kontiki Client",
            "LeechFTP",
            "LeechGet",
            "LightningDownload",
            "Mass Downloader",
            "MetaProducts",
            "NetAnts",
            "NetButler",
            "NetPumper",
            "Net Vampire",
            "Nitro Downloader",
            "Octopus",
            "PuxaRapido",
            "RealDownload",
            "SpeedDownload",
            "WebDownloader",
            "WebLeacher",
            "WebPictures",
            "X-Uploader",
            "DigOut4U",
            "DISCoFinder",
            "eCatch",
            "EirGrabber",
            "ExtractorPro",
            "FairAd Client",
            "iSiloWeb",
            "Kenjin Spider",
            "MSIECrawler", "MSProxy",
            "NexTools",
            "Offline Explorer",
            "NetAttache",
            "PageDown",
            "ParaSite",
            "Searchworks Spider",
            "SiteMapper",
            "SiteSnagger",
            "SuperBot",
            "Teleport Pro",
            "Web2Map",
            "WebAuto",
            "WebCopier",
            "Webdup",
            "WebFetch",
            "WebReaper",
            "Webrobot",
            "Website eXtractor",
            "WebSnatcher",
            "WebStripper",
            "WebTwin",
            "WebVCR",
            "WebZIP",
            "WWWOFFLE",
            "Xaldon WebSpider",
            "spbot",
            "Qwantify",
            "BLEXBot", 'blexbot',
            "istellabot",
            "YandexImages",
            "facebot",
            "linkpadbot",
            "siteexplorer",
            "adidxbot",
            "bnsbot",
            "bingpreview",
            "megaindex",
        ];


    public function __construct() {
        $data = implode('|', $this->data);


        $data = str_replace('.', '\.', $data);
        $data = str_replace('\\', '\\\\', $data);
        $data = str_replace('/', '\/', $data);
        $data = str_replace('+', '\+', $data);

        $this->data = explode($data, '|');
    }

}