#!/bin/bash
rm /home/feeds/test_mainfeeds_progress.txt
echo " " >> /home/feeds/test_mainfeeds_progress.txt
echo "Start processing" >> /home/feeds/test_mainfeeds_progress.txt
cd /var/www/test.stores/dev1/
php5 ./launch_main_product_feeds.php >> /home/feeds/test_mainfeeds_progress.txt
