#!/bin/bash
flag="/home/feeds/amazon_orders_import.flg"
if [ -e /home/feeds/amazon_orders_import.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/amazon_orders_import.flg
    rm /home/feeds/amazon_orders_import_progress.txt
    echo " " >> /home/feeds/amazon_orders_import_progress.txt
    echo "Start processing" >> /home/feeds/amazon_orders_import_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_amazon_orders.php >> /home/feeds/amazon_orders_import_progress.txt

    echo " " >> /home/feeds/amazon_orders_import_progress.txt
    echo "Finish processing" >> /home/feeds/amazon_orders_import_progress.txt
    rm /home/feeds/amazon_orders_import.flg
fi

