#!/bin/bash
flag="/home/feeds/amazon_fba_info_reserved_inventory.flg"
if [ -e /home/feeds/amazon_fba_info_reserved_inventory.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/amazon_fba_info_reserved_inventory.flg
    rm /home/feeds/amazon_fba_info_reserved_inventory_progress.txt
    echo " " >> /home/feeds/amazon_fba_info_reserved_inventory_progress.txt
    echo "Start processing" >> /home/feeds/amazon_fba_info_reserved_inventory_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_amazon_info.php reserved_inventory 1>> /home/feeds/amazon_fba_info_reserved_inventory_progress.txt

    echo " " >> /home/feeds/amazon_fba_info_reserved_inventory_progress.txt
    echo "Finish processing" >> /home/feeds/amazon_fba_info_reserved_inventory_progress.txt
    rm /home/feeds/amazon_fba_info_reserved_inventory.flg
fi

