#!/bin/bash
flag="/home/feeds/amazon_fee_report.flg"
if [ -e /home/feeds/amazon_fee_report.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/amazon_fee_report.flg
    rm /home/feeds/amazon_fee_report_progress.txt
    echo " " >> /home/feeds/amazon_fee_report_progress.txt
    echo "Start processing" >> /home/feeds/amazon_fee_report_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_amazon_fee_report.php >> /home/feeds/amazon_fee_report_progress.txt

    echo " " >> /home/feeds/amazon_fee_report_progress.txt
    echo "Finish processing" >> /home/feeds/amazon_fee_report_progress.txt
    rm /home/feeds/amazon_fee_report.flg
fi

