#!/bin/bash
flag="/home/feeds/amazon_inbound_shipments.flg"
if [ -e /home/feeds/amazon_inbound_shipments.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/amazon_inbound_shipments.flg
    rm /home/feeds/amazon_inbound_shipments_progress.txt
    echo " " >> /home/feeds/amazon_inbound_shipments_progress.txt
    echo "Start processing" >> /home/feeds/amazon_inbound_shipments_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_amazon_list_inbound_shipment_items.php >> /home/feeds/amazon_inbound_shipments_progress.txt

    echo " " >> /home/feeds/amazon_inbound_shipments_progress.txt
    echo "Finish processing" >> /home/feeds/amazon_inbound_shipments_progress.txt
    rm /home/feeds/amazon_inbound_shipments.flg
fi

