#!/bin/bash
flag="/home/feeds/amazon_fba_info_lowest_offer.flg"
if [ -e /home/feeds/amazon_fba_info_lowest_offer.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/amazon_fba_info_lowest_offer.flg
    rm /home/feeds/amazon_fba_info_lowest_offer_progress.txt
    echo " " >> /home/feeds/amazon_fba_info_lowest_offer_progress.txt
    echo "Start processing" >> /home/feeds/amazon_fba_info_lowest_offer_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_amazon_info.php lowest_offer 1>> /home/feeds/amazon_fba_info_lowest_offer_progress.txt

    echo " " >> /home/feeds/amazon_fba_info_lowest_offer_progress.txt
    echo "Finish processing" >> /home/feeds/amazon_fba_info_lowest_offer_progress.txt
    rm /home/feeds/amazon_fba_info_lowest_offer.flg
fi

