#!/bin/bash
flag="/home/feeds/inc_feeds.flg"
if [ -e /home/feeds/classified_products_watchdog.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/classified_products_watchdog.flg
    rm /home/feeds/classified_products_watchdog_progress.txt
    echo " " >> /home/feeds/classified_products_watchdog_progress.txt
    echo "Start processing" >> /home/feeds/classified_products_watchdog_progress.txt
    cd /var/www/stores/cron/
    php5 ./cron_auto_classified_products_watchdog.php >> /home/feeds/classified_products_watchdog_progress.txt

    echo " " >> /home/feeds/classified_products_watchdog_progress.txt
    echo "Finish processing" >> /home/feeds/classified_products_watchdog_progress.txt
    rm /home/feeds/classified_products_watchdog.flg
fi

