#!/bin/bash
echo "Start processing" >> /home/feeds/cu_progress.txt
cd /var/www/stores/
php5 ./cidev_generate_clean_urls.php >> /home/feeds/cu_progress.txt
rm /home/feeds/cu_progress.txt
echo " " >> /home/feeds/cu_progress.txt
