#!/bin/bash
flag="/home/feeds/cron_monitor.flg"
if [ -e /home/feeds/cron_monitor.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/cron_monitor.flg
    rm /home/feeds/cron_monitor_progress.txt
    echo " " >> /home/feeds/cron_monitor_progress.txt
    echo "Start processing" >> /home/feeds/cron_monitor_progress.txt
    cd /var/www/stores/
    php5 ./cron_processes.php >> /home/feeds/cron_monitor_progress.txt

    echo " " >> /home/feeds/cron_monitor_progress.txt
    echo "Finish processing" >> /home/feeds/cron_monitor_progress.txt
    rm /home/feeds/cron_monitor.flg
fi

