#!/bin/bash
flag="/home/feeds/dispatch_off_hours.flg"
if [ -e /home/feeds/dispatch_off_hours.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/dispatch_off_hours.flg
    rm /home/feeds/dispatch_off_hours_progress.txt
    echo " " >> /home/feeds/dispatch_off_hours_progress.txt
    echo "Start processing" >> /home/feeds/dispatch_off_hours_progress.txt
    cd /var/www/stores/
    php ./cron_dispatch_to_distributor.php >> /home/feeds/dispatch_off_hours_progress.txt

    echo " " >> /home/feeds/dispatch_off_hours_progress.txt
    echo "Finish processing" >> /home/feeds/dispatch_off_hours_progress.txt
    rm /home/feeds/dispatch_off_hours.flg
fi

