#!/bin/bash
test "$(date +%a)" == 'Sat' -a "$((($(date +%-d)-1)/7+1))" == 3 && (
rm /home/feeds/google_progress.txt
echo "Start processing Sat" >> /home/feeds/google_progress.txt
cd /var/www/stores/
php5 ./cron_feedsupdate.php >> /home/feeds/google_progress.txt
echo " " >> /home/feeds/google_progress.txt
)

