#!/bin/bash
flag="/home/feeds/gmc_expired_and_issues.flg"
if [ -e /home/feeds/gmc_expired_and_issues.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/gmc_expired_and_issues.flg
    rm /home/feeds/gmc_expired_and_issues_progress.txt
    echo " " >> /home/feeds/gmc_expired_and_issues_progress.txt
    echo "Start processing" >> /home/feeds/gmc_expired_and_issues_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_google_product_statuses.php 1>> /home/feeds/gmc_expired_and_issues_progress.txt

    echo " " >> /home/feeds/gmc_expired_and_issues_progress.txt
    echo "Finish processing" >> /home/feeds/gmc_expired_and_issues_progress.txt
    rm /home/feeds/gmc_expired_and_issues.flg
fi

