#!/bin/bash
flag="/home/feeds/inc_feeds.flg"
if [ -e /home/feeds/inc_feeds.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/inc_feeds.flg
    rm /home/feeds/inc_feeds_progress.txt
    echo " " >> /home/feeds/inc_feeds_progress.txt
    echo "Start processing" >> /home/feeds/inc_feeds_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_incremental_feeds.php >> /home/feeds/inc_feeds_progress.txt

    echo " " >> /home/feeds/inc_feeds_progress.txt
    echo "Finish processing" >> /home/feeds/inc_feeds_progress.txt
#    cp /home/feeds/inc_feeds_progress.txt /home/igor/inc_feeds_copy
    rm /home/feeds/inc_feeds.flg
fi

