#!/bin/bash
flag="/home/feeds/paypal_watchdog.flg"
if [ -e /home/feeds/paypal_watchdog.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/paypal_watchdog.flg
    rm /home/feeds/paypal_watchdog_progress.txt
    echo " " >> /home/feeds/paypal_watchdog_progress.txt
    echo "Start processing" >> /home/feeds/paypal_watchdog_progress.txt
    cd /var/www/stores/cron
    php5 ./cron_paypal_transactions_watchdog.php >> /home/feeds/paypal_watchdog_progress.txt

    echo " " >> /home/feeds/paypal_watchdog_progress.txt
    echo "Finish processing" >> /home/feeds/paypal_watchdog_progress.txt
    rm /home/feeds/paypal_watchdog.flg
fi

