#!/bin/bash
flag="/home/feeds/sfeed_feeds.flg"
if [ -e /home/feeds/sfeed_feeds.flg ]
then
    echo "Already running..."
else
    echo " " >> /home/feeds/sfeed_feeds.flg
    rm /home/feeds/sfeed_feeds_progress.txt
    echo " " >> /home/feeds/sfeed_feeds_progress.txt
    echo "Start processing" >> /home/feeds/sfeed_feeds_progress.txt
    cd /var/www/stores/cron
    php ./cron_supplier_feeds.php P 1>> /home/feeds/sfeed_feeds_progress.txt
    echo " " >> /home/feeds/sfeed_feeds_progress.txt
    echo "Finish processing" >> /home/feeds/sfeed_feeds_progress.txt
    rm /home/feeds/sfeed_feeds.flg
fi
