#!/bin/bash
flag="/home/feeds/thumbs_generate.flg"
if [ -e /home/feeds/thumbs_generate.flg ]
then
    echo "Already running..."
    
else
    echo " " >> /home/feeds/thumbs_generate.flg
    rm /home/feeds/thumbs_generate_progress.txt
    echo " " >> /home/feeds/thumbs_generate_progress.txt
    echo "Start processing" >> /home/feeds/thumbs_generate_progress.txt
    cd /var/www/stores/
    php ./cidev_image_generator.php >> /home/feeds/thumbs_generate_progress.txt

    echo " " >> /home/feeds/thumbs_generate_progress.txt
    echo "Finish processing" >> /home/feeds/thumbs_generate_progress.txt
    rm /home/feeds/thumbs_generate.flg
fi

