    fastcgi_cache_key "$scheme$request_method$host$request_uri$cookie_codeAuth";

    ## TODO turn caching on in production, set to 0
    set $no_cache 1;

    if ($request_uri ~ "/api/") {
        set $no_cache 1;
    }

    if ($request_uri ~ "/cart/") {
        set $no_cache 1;
    }

    if ($request_uri ~ "/checkout/") {
        set $no_cache 1;
    }

    if ($request_uri ~ "/account/") {
        set $no_cache 1;
    }

    if ($request_uri ~ "/admin/") {
        set $no_cache 1;
    }

    if ($request_uri ~ "/api/category/featured") {
        set $no_cache 0;
    }

    if ($request_uri ~ "/api/category/new") {
        set $no_cache 0;
    }

    if ($request_uri ~ "/api/category/bestsellers") {
        set $no_cache 0;
    }

    if ($request_uri ~ "/api/category/.*/new-products/") {
        set $no_cache 0;
    }

    ## TODO turn caching on in production, remove it
    set $no_cache 1;