    ssl_certificate /etc/letsencrypt/live/s3stores/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/s3stores/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/s3stores/chain.pem;

    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 127.0.0.1 8.8.8.8;