<?php
/**
 * Created by PhpStorm.
 * User: maksim
 * Date: 31.10.17
 * Time: 17:57
 */

namespace Modules\Cart\Forms\CouponRestrictions;


use Modules\Cart\Discounts\Restrictions\BrandRestriction;
use Modules\Cart\Discounts\Restrictions\CountUsedRestriction;
use Modules\Cart\Forms\DiscountRestrictionForm;
use Xcart\App\Form\Fields\Select2Field;

class BrandRestrictionForm extends DiscountRestrictionForm
{
    public static function getRestrictClass()
    {
        return BrandRestriction::className();
    }

    public function getFields()
    {
        $data = $this->getInstance()->data;

        return array_merge(parent::getFields(), [
            'brand' => [
                'class' => Select2Field::className(),
                'value' => empty($data['brand']) ? null : $data['brand'],
            ],
        ]);
    }

    public function save()
    {
//        $data = $this->getInstance()->data;
//        $this->cleanedData['uses'] = empty($data['uses']) ? 0: $data['uses'];

        return parent::save(); // TODO: Change the autogenerated stub
    }
}