<?php
/**
 * Created by PhpStorm.
 * User: maksim
 * Date: 31.10.17
 * Time: 17:57
 */

namespace Modules\Cart\Forms\CouponRestrictions;


use Modules\Cart\Discounts\Restrictions\CountUsedRestriction;
use Modules\Cart\Forms\DiscountRestrictionForm;
use Xcart\App\Form\Fields\NumberField;

class CountUsesForm extends DiscountRestrictionForm
{
    public static function getRestrictClass()
    {
        return CountUsedRestriction::className();
    }

    public function getFields()
    {
        $data = $this->getInstance()->data;

        return array_merge(parent::getFields(), [
            'max_use' => [
                'class' => NumberField::className(),
                'required' => true,
                'value' => empty($data['max_use']) ? 1: $data['max_use'],
            ],
            'max_uses_per_user' => [
                'class' => NumberField::className(),
                'required' => true,
                'value' => empty($data['max_uses_per_user']) ? 1: $data['max_uses_per_user'],
            ],
            'uses' => [
                'class' => NumberField::className(),
                'required' => true,
                'value' => empty($data['uses']) ? 0: $data['uses'],
                'html' => [
                    'disabled' => 'disabled',
                ]
            ],
        ]);
    }

    public function save()
    {
        $data = $this->getInstance()->data;
        $this->cleanedData['uses'] = empty($data['uses']) ? 0: $data['uses'];

        return parent::save(); // TODO: Change the autogenerated stub
    }
}