<?php
namespace Modules\Payment\Gateways;

class Sberbank extends Gateway
{
    public static function getProcessorName()
    {
        return 'Sberbank'; // TODO: Change the autogenerated stub
    }
    public function success($params)
    {
        parent::success($params); // TODO: Change the autogenerated stub
    }

    public function __construct($model)
    {
        parent::__construct($model);
    }

    public function refund($params)
    {
        // TODO: Implement refund() method.
    }

    public function void($params)
    {
        // TODO: Implement void() method.
    }

    public function capture($params)
    {
        // TODO: Implement capture() method.
    }

    public function lookup($params)
    {
        // TODO: Implement lookup() method.
    }

    public function authorize($params)
    {
        $this->gateway->setTestMode(true);
        $timestamp = time();
        $this->result = $this->gateway->authorize(
            [
                'orderNumber' => "{$params['order']->pk}_$timestamp",
                'amount' => $params['amount'],
                'returnUrl' => $params['returnUrl'],
                'description' => $params['description'],
                'dynamicCallbackUrl' => "http://147.182.142.64/payment/success/sberbank"
            ]
        )->setTwoStage(true)->setUserName('T4345468446-api')->setPassword('T4345468446')->send();
    }

    public function reauthorize($params)
    {
        // TODO: Implement reauthorize() method.
    }

    public function purchase($params)
    {
        $this->authorize($params);
        return $this->result->isSuccessful();
        // TODO: Implement purchase() method.
    }

    public function complete($params)
    {
        // TODO: Implement complete() method.
    }

    public function getState($mode)
    {
        // TODO: Implement getState() method.
    }
}